### ISSUE TITLE
Dúvida.

### ISSUE THREAD

**Issue by PhilipACM** [gustavoguanabara/git-github#1]
Olá professor! boa tarde. estou com uma dificuldade, abrir um repositório das aulas de html que eu testou fazendo com o senhor, mas por falta de atenção eu coloquei como privada, teria como me ensinar como colocar ela em público? ou eu tenho que apagar e abrir de novo como público?

**Comment by gustavoguanabara** [comment]
Olá, @PhilipACM ! Dá pra mudar sim! Abra seu repositório e na barra superior, clique em **Settings**. Lá no final vai ter uma opção para tornar seu repositório público. Leia atentamente os avisos e aceite. 🖖 
![Gustavo Guanabara](https://user-images.githubusercontent.com/8683378/78829889-82e44800-79bd-11ea-8c43-c01dec380edf.png)
* Coisas grátis no [GitHub](https://gustavoguanabara.github.io) 
* Segue lá no [Instagram](https://www.instagram.com/gustavoguanabara/)
* Se inscreve lá no [YouTube](https://www.youtube.com/cursoemvideo)

**Comment by PhilipACM** [comment]
obrigado professor...  resolução feita, mas só vim responder que deu certo por que eu vi na aula hoje que o senhor estava esperando eu falar para poder fechar a issues kkk, mas não por nada só por que pensei que dando certo poderia ser um incomodo falar mais aqui. 
obg abraços

**Comment by gustavoguanabara** [comment]
Sempre volte para agradecer! É uma boa prática aqui na comunidade! 🖖
