### ISSUE TITLE
Minha Game Engine feita em Python

### ISSUE THREAD

**Issue by aragubas** [gustavoguanabara/git-github#102]
A game engine se chama Taiyou Game Engine, fiz ela usando Python e Pygame puro
- Ela tem:
1. Sistema de Registro
2. Função de Carrega/Descarrega Sprite
3. Gerenciamento de Janela *janela do pygame*

[Link da pagina do Github](https://github.com/aragubas/taiyou-game-engine)

**Comment by christyanbrayan** [comment]
posta na issue #3

**Comment by christyanbrayan** [comment]
e fecha essa

**Comment by fednerdabady** [comment]
> A game engine se chama Taiyou Game Engine, fiz ela usando Python e Pygame puro
> 
> * Ela tem:
> 
> 1. Sistema de Registro
> 2. Função de Carrega/Descarrega Sprite
> 3. Gerenciamento de Janela _janela do pygame_
> 
> [Link da pagina do Github](https://github.com/aragubas/taiyou-game-engine)

legal 👍
