### ISSUE TITLE
Onde estão os slides da Aula 04?

### ISSUE THREAD

**Issue by andersonmeurer** [gustavoguanabara/git-github#1032]
Teste!. Procurei os slides da aula 04 e não encontrei. Teste!.

**Comment by RenatoAlbuquerque** [comment]
kkkkkkkkk eu tava assistindo essa aula também, mas apaga a issue se não vai ser considerada spam @andersonmeurerr

**Comment by yvesantoci** [comment]
kkkkkkkkkkkkk engraçado

**Comment by yvesantoci** [comment]
Eu to vendo essa aula também hoje 22/06/2021

**Comment by andersonmeurer** [comment]
> kkkkkkkkk eu tava assistindo essa aula também, mas apaga a issue se não vai ser considerada spam @andersonmeurerr

Obrigado

**Comment by andersonmeurerr** [comment]
Estou gostando do curso, e vc esta curtindo ?

**Comment by andersonmeurer** [comment]
> Eu to vendo essa aula também hoje 22/06/2021

Estou gostando do curso, e vc esta curtindo ?
