### ISSUE TITLE
Onde estão os slides da aula 4?

### ISSUE THREAD

**Issue by LuizBrandi** [gustavoguanabara/git-github#1056]
"Procurando" slides da 4ª aula!!  🤭

**Comment by JeanPaulino51** [comment]
tambem quero saber

**Comment by francislopes** [comment]
Boa pergunta

**Comment by mandamg** [comment]
A aula 04 não teve slides, foi sobre as instalações necessárias para a utilização do Git. (TESTE kkk)

**Comment by LuizBrandi** [comment]
Como não achei, vou fechar essa issue.
