### ISSUE TITLE
As consequencias são tragicas se eu mudar meu username no github?

### ISSUE THREAD

**Issue by RonanJordao** [gustavoguanabara/git-github#106]
Estou dando uma  repaginada no meu perfil do github para ficar mais profissional como o @gustavoguanabara recomendou.E estava desejando mudar o meu username de @ronanProg para @ronanJordao se fosse possível.Mas ao tentar alterar o username recebi a messagem que isso não é aconselhavel de se fazer.Pois poderá ter consequências inesperadas.

Alguem já mudou o nome de usuário do github e teve grandes consequencias negativas ao fazer isso?

![mudar-username](https://user-images.githubusercontent.com/19637278/79152915-037abe00-7d9b-11ea-8813-b8f4ad907fcd.png)

**Comment by leocunhabr** [comment]
Todos os caminhos dos seus repositórios iram mudar o link para encontrá-los, para quem está começando agora não é tão preocupante, porque você ainda não está recebendo contribuições de outras pessoas, não tem seu repositórios clonados ou copiados e usados de exemplo em outros locais.

Não minha visão não teria problema muito GRAVES para você.

**Comment by ronanProg** [comment]
obrigado @leocunhabr .Outra dúvida.Existe um padão para criar username?Como por exemplo: Precisa ser todos os caracteres minusculos.

**Comment by leocunhabr** [comment]
Te aconselho a usar todos os caracteres minúsculos e algo fácil de lembrar, fica mais fácil conforme você vai (por exemplo) clonando seus repositórios.
```
git clone https://github.com/{seunome}/{seurepositorio}.git
```
A escrita fica mais fluida e intuitiva, além outras vantagens.

**Comment by RonanJordao** [comment]
Valeu @leocunhabr :+1:  .Foram ótimas dicas.
