### ISSUE TITLE
Como criar e excluir pastas(diretórios) no GitHub?

### ISSUE THREAD

**Issue by ronan-jordao** [gustavoguanabara/git-github#107]
Estou tentando dar uma organização no meu repositório de exercícios do Estudonauta.Mas o problema está na criação de pastas e subpastas.Que ainda não consigo acertar no GitHub.

Estou tentando criar assim o diretórior:

1-Algoritmos (Portugol Studio)     ---->Pasta
      Módulo 0 - Primeiros passos  --->Subpasta
          Aula 1 ----->arquivos
          Aula 2

E preciso saber como deletar arquivos e pastas no GitHub.Pois errei.A única forma que sei fazer até agora é excluir e refazer repositório para corrigir.Mas é tipo uma gambiarrra

Alguém pode me ajudar?

**Comment by RodrigoPiropo** [comment]
Já tentou melhorar isso no git alterando localmente as pastas etc... e subir para o github?

**Comment by Cpharles** [comment]
@ronan-jordao tudas as auterações que vc fizer no seu repositório, será automaticamente atualiazado no seu GitHub depois que vc fizer um puch. Então a dica é, monte a estrutura do geito que vc quiser no seu repositório local e depois suba para o GitHub.

**Comment by ronan-jordao** [comment]
@RodrigoPiropo  e @Cpharles .Eu já tentei fazer no repositório local e depois dar um push para o gitHub.Mas  pela 2 vezes que tentei.Acaba anulando a subpasta módulo 0 por exemplo.

**Comment by Cpharles** [comment]
@ronan-jordao . Eu dei uma olhada na sua pasta e vi que vc adicionou um diretório "Modulo 00-..." é esta pasta??, mas ainda não entendi direito o que esta dando errado!.  Eu fiz um teste em um  repositório meu e adicionei algumas pastas e arquivos, com a nomenclatura, acredito eu que é o que vc quer fazer, dá uma olhada lá [Olá Mundo](https://github.com/Cpharles/OlaMundo)

**Comment by ronan-jordao** [comment]
@Cpharles descobri o erro.Inicialmente fiz algo como Algoritmos/Módulo 00/ arquivo 01.Assim quando "abria" a pasta algoritmos logo entrava dentro do modulo 00 com os arquivos.Assim que acionei mais pastas de módulos.Começou a ficar visível.Nao sei se consegui explicar direito o que estava acontecendo.Mas foi mais ou menos assim.
