### ISSUE TITLE
Onde está os slide da Aula04 ??

### ISSUE THREAD

**Issue by RoberttReis** [gustavoguanabara/git-github#1074]
Procurei os slide da aula 04 :/

**Comment by MuriloNSantos17** [comment]
Olá @RoberttReis, aparentemente não temos slides da Aula 04, porém você pode encontrar os slides das demais aulas no link a seguir: https://github.com/gustavoguanabara/git-github/tree/master/slides-aulas . 

Espero ter ajudado.
