### ISSUE TITLE
Porque você está lendo isso?

### ISSUE THREAD

**Issue by KaueGuimaraes** [gustavoguanabara/git-github#1167]
Eu gostaria de saber porque você está lendo isso? Com todo respeito, você não tem mais o que fazer não?

**Comment by EmersonLR** [comment]
E eu rebato com outra pergunta, quem veio primeiro o ovo ou a galinha??

**Comment by KaueGuimaraes** [comment]
@EmersonLR O ovo.

**Comment by EmersonLR** [comment]
Pq o ovo? sendo que não existia nenhuma galinha para botá lo..

**Comment by KaueGuimaraes** [comment]
Já dizia o Metaforando, o mentiroso evita responder diretamente e geralmente rebate uma pergunta com outra pergunta.

![749a6292a2a39123f0ac37ce66f48d37d54f2e01ce5edf9d4491c9b86f00f02f_1](https://user-images.githubusercontent.com/76141331/129414117-c31e1c4a-bc6b-4cae-9dcf-a8c11f6932dd.jpg)

**Comment by EmersonLR** [comment]
kkkk Boa, eu vi o vitor falar isso msm kkk

**Comment by KaueGuimaraes** [comment]
@EmersonLR Porque você quer saber isso? 😎

**Comment by EmersonLR** [comment]
@KaueGuimaraes  estou brincando e testando o github hsauhsuahushus, to fazendo o curso do guanabara de git

**Comment by KaueGuimaraes** [comment]
@EmersonLR em que tempo da aula?

**Comment by EmersonLR** [comment]
to na aula de Issues, ai ele ensina a mandar comentario em uma issue

**Comment by KaueGuimaraes** [comment]
Entendi, aí sim.

**Comment by EmersonLR** [comment]
Very nice !

**Comment by KaueGuimaraes** [comment]
Eu tô nessa aula também, 25:20

**Comment by EmersonLR** [comment]
to no 25:28 shaushuashua

**Comment by KaueGuimaraes** [comment]
😎

**Comment by EmersonLR** [comment]
😆

**Comment by KaueGuimaraes** [comment]
[Projeto](https://github.com/ACultist/Novypad-Notepad)

**Comment by KaueGuimaraes** [comment]
Adeus

**Comment by KaueGuimaraes** [comment]
teste

**Comment by EmersonLR** [comment]
see you later !
