### ISSUE TITLE
Testando Linguagem Mark down 😀

### ISSUE THREAD

**Issue by Matheus-github** [gustavoguanabara/git-github#1172]
Estou aprendendo linguagem **MarkDown** no __Curso Em Vídeo__

# aula curso em vídeo
***
## Aprendendo Linguagem Markdown
***
### Testando Linguagem MarkDown

Lista Numerada

1. Teste1
1. Teste2
1. Teste3
123. Teste4

Lista Demarcada:

* Teste
* Teste
   * teste
Lista de Tarefas:

- [x] Criar pagina principal do site
- [ ] Criar Pagina de Pagamentos

**Comment by Matheus-github** [comment]
![Wallpaper 1](https://user-images.githubusercontent.com/63616702/129607637-3058b2e8-8013-49ed-b2f8-86f73c7c30cc.jpg)

[Acesse meu Github](https://github.com/Matheus-github)

Tabela:

Num | Nome | Nota
---|---|---
1 | Matheus Kauã | 10,0
2 | João | 8,0
3 | Carlos | 9,5

**Comment by Matheus-github** [comment]
Pra que serve o comando `document.getElementById()` (TESTE) 

Exemplo de programa em Python:

```
num = int(input("Digite um valor:"))
print("O valor que você digitou foi + num")

```

**Comment by Matheus-github** [comment]
Testando emojis:

👍 
🐶 
🐱 
🚓 
🌔

**Comment by Matheus-github** [comment]
Citando pessoas:

@gustavoguanabara 
@Matheus-github  

> ola mundo

**Comment by webersonclw** [comment]
testando mark __markdown__ em *git*
testando mark ~~markdown~~ em *git*

# Aula de Mark
***
## podemos __*misturar*__ configurações
### titulo

# listar numeros
1. test
   1. test1
   2. test2
3. test3

# lista demarcada
- test 
* test
   * test
   * test

# lista de tarefas
- [X] tenho q aprender Git
- [x] tenho q aprender Python
- [ ] desenvolver um site
- [ ] responder a todos

**Comment by webersonclw** [comment]
![diga não ao racismo](https://user-images.githubusercontent.com/91290514/134828344-5164a79b-0afa-4d04-b5af-93d9f80ba8e5.jpg)

**Comment by webersonclw** [comment]
Num | Nome | Nota
--- | --- | ---
1 | Weberson | 9.0
2 | Malu | 8.5
3 | Pedro | 9.5

# termino de tabela 👍 🖖 🤙 🙉
