### ISSUE TITLE
TESTANDO LINGUAGEM MARKDOWN

### ISSUE THREAD

**Issue by ghost** [gustavoguanabara/git-github#1235]
Podemos _**misturar**_ configurações!!
****

Lista numerada: 

1. Estudar 
20. fazer tarefas de casa:
    2.1 Matemática e Português
33. Estudar para a avaliação bimestral.
 ***

Lista demarcada

* Ir ao mercado 
* Criar a página principal do site
  
***
Lista de tarefas:

- [ ] Terminar curso 
- [x] Agradecer ao Professor 
***

![685ac6cc9bde3f25827fed0ffcffbcf4 (2)](https://user-images.githubusercontent.com/89478384/132954002-10679665-d1bb-4031-85d6-161d8e22fdf4.jpg)

**Comment by rovan-83** [comment]
#Título# 
estou aprendendo **linguagem** md no __curso__ de git e ~~github~~
---

1. ddd
2. dfwef
3. ewrw
4.       i.fhjdhfsh
5. sa
lista de tarefas 
[x] esdada
[ ] adad
![sei la oq etufo](https://user-images.githubusercontent.com/90455673/134051528-5f74f1bd-9793-4d2e-acde-2ede17191f6b.jpg)
a

**Comment by rovan-83** [comment]
Num| Nome| Nota
---|---|---
1|GUstavo| 2,3
3| teste| sen nota

**Comment by rovan-83** [comment]
como diria 

> 
> ## #Título#
> estou aprendendo **linguagem** md no **curso** de git e ~github~
> 
>     1. ddd
> 
>     2. dfwef
> 
>     3. ewrw
> 
>     4. ```
>          i.fhjdhfsh
>        ```
> 
>     5. sa
>        lista de tarefas
>        [x] esdada
>        [ ] adad
>        ![sei la oq etufo](https://user-images.githubusercontent.com/90455673/134051528-5f74f1bd-9793-4d2e-acde-2ede17191f6b.jpg)
>        a

agota q vi  pode
