### ISSUE TITLE
Rafael Naves, perfil @rafaelfnaves.

### ISSUE THREAD

**Issue by rafaelfnaves** [gustavoguanabara/git-github#124]
Meu Nome é Rafael Naves, meu perfil é @rafaelfnaves
Meus melhores projetos atualmente:
- [Project ToDo](https://github.com/rafaelfnaves/todo) 

- [Project Be-The-Hero](https://github.com/rafaelfnaves/be-the-hero)

**Comment by rafaelseixista** [comment]
opa, olá colega, ainda estou aprendendo javascript e git/github aqui no curso do Guanabara mas vou seguir seu perfil pra participar aqui da comunidade
