### ISSUE TITLE
Onde está os slides da Aula 4?

### ISSUE THREAD

**Issue by AnaRoling** [gustavoguanabara/git-github#1249]
Procurei os slides da aula 4 e não encontrei. Alguém poderia atualizar para mim?

**Comment by Hydro-GMVB** [comment]
Oi Ana, lembra que esta foi uma aula _prática_. Podes checar na playlist [clicando aqui](https://www.youtube.com/playlist?list=PLHz_AreHm4dm7ZULPAmadvNhH6vk9oNZA).

**Bons estudos!**

**Comment by DeveloperHS2021** [comment]
Também quero saber.

**Comment by MasterSix997** [comment]
faço a minima
