### ISSUE TITLE
Markdown nao funcionando no ReadMe.md

### ISSUE THREAD

**Issue by leonardoscherrer** [gustavoguanabara/git-github#126]
Estou fazendo o curso de Git-GitHub do Guanabara. Porém quando cheguei na aula de Linguagem Markdown, mais especificamente na parte de sublinhar o texto no ReadMe, não foi possível alterá-lo

Iniciei e finalizei a palavra com 2 asterísticos '**'. No entanto, quando clico em salvar, a mensagem selecionada não é sublinhada, ficando apenas com os **...** na tela do ReadMe.

Irei disponibilizar o print da imagem:

![image](https://user-images.githubusercontent.com/63501719/79593104-57deb000-80b1-11ea-9999-005ad3913b1e.png)

**Comment by ronan-jordao** [comment]
@leonardoscherrer o simbolo `**Palavra**` que está usando é para deixar a palavra em negrito para deixar sublinhado se usa `~~Palavra~~`.
Exemplo:  **Negrito**  e ~~Sublinhado~~

**Comment by matheussantanads** [comment]
Então, @leonardoscherrer na verdade '**' não sublinha a palavra/texto, ele deixa em negrito. Acessei o teu repositório para verificar onde estava o possível erro, ao abrir o Readme.md me deparei com a seguinte situação:
![img1](https://user-images.githubusercontent.com/22276409/79608976-48209500-80cc-11ea-9da1-2ecd3ce7c73b.png)
Existe um espaçamento (até grandinho kk) em branco nos seus parágrafos, isso fez com que a linguagem Markdown não interpretasse de maneira correta o teu texto, afim de corrigir isso você teria que deixar os textos alinhados a esquerda, ou seja, sem esse espaçamento em branco, como segue na próxima imagem.
![img2](https://user-images.githubusercontent.com/22276409/79609082-7ef6ab00-80cc-11ea-84df-3fbf2ca53f6b.png)
Dessa forma o teu Readme ficará assim:
![img3](https://user-images.githubusercontent.com/22276409/79609118-8d44c700-80cc-11ea-869d-977a2294e656.png)

E como expliquei no inicio '**' é para negrito, para sublinhar você deve seguir a dica do @ronan-jordao

**Comment by leonardoscherrer** [comment]
Opa! Essa aba de Issues funciona mesmo!
Valeu pela ajuda @ronan-jordao e @matheussantanads 
**Grato demais!** :smile:
