### ISSUE TITLE
Testando a Linguagem Markdown!

### ISSUE THREAD

**Issue by EderCruzz** [gustavoguanabara/git-github#1260]
Vou testar a linguagem Markdown.

**Comment by EderCruzz** [comment]
# Aula de linguagem Markdown
---
## Título 2
***
### Título 3

Estou aprendendo __*linguagem*__ **Markdown** no *curso* em _video_ de ~~git e github~~.

lista numerada:

1. Teste
2. Teste
3. Teste
4. teste
5. tsdfse
6. 234efcs
7.  23243
    1. adsdw 
    2. adsdwae
    3.  21r23


Lista demarcada:

* Teste
* Teste
* Teste
    * Teste
    * testes

Lista de Tarefas:

- [x] Criar a pagina principal
- [x] Criar a página da loja
- [ ] Finalizar a reunião com o cliente
- [ ] Receber pagamento

**Comment by EderCruzz** [comment]
![Octocat da Galaxia](https://user-images.githubusercontent.com/90397436/134816018-cc3f9dd9-31f6-4403-99db-01ab54882ee8.png)
---
[Acesse meu GitHub](https://github.com/EderCruzz)

**Comment by EderCruzz** [comment]
# Criando Tabela
---

Num | Nome | Nota
---|---|---
1|Eder|10
2|Gustavo|10
3|João|8,5

**Comment by EderCruzz** [comment]
# Postando códigos
---


Não entendo direito para que serve o comando `documento.getElementById()` da linguagem JavaScript

Olha meu programa de PAR ou IMPAR em python!
```
num = int(input('Digite um valor: '))
if num % 2 == 0:
       print(f'O valor {num} é PAR!')
else:
       print(f'O valor {num} é IMPAR!)
```

**Comment by EderCruzz** [comment]
Usando Emoji
---

Olá pequeno gafanhoto 🖖 ✋ 🖤

**Comment by EderCruzz** [comment]
> # Postando códigos
> Não entendo direito para que serve o comando `documento.getElementById()` da linguagem JavaScript
> 
> Olha meu programa de PAR ou IMPAR em python!
> 
> ```
> num = int(input('Digite um valor: '))
> if num % 2 == 0:
>        print(f'O valor {num} é PAR!')
> else:
>        print(f'O valor {num} é IMPAR!)
> ```


Muito legal sua postagem

**Comment by EderCruzz** [comment]
Entre em contato:

* Meu perfil no [Instagram](https://www.instagram.com/edi_cruz_/)
* Meu perfil no [LinkedIn](https://www.linkedin.com/in/eder-cruz-2b6366218/)

**Comment by Liineker** [comment]
Num | Nome | Nota 
---|---|---
1 | Gustavo | 8,5
2 | José | 10
3 | Maria | 9

```
num
```

Olá, pequeno gafanhoto:vulcan_salute
