### ISSUE TITLE
Qual é o horario das aulas?

### ISSUE THREAD

**Issue by Amir258** [gustavoguanabara/git-github#127]
# Queria saber o cronograma das aulas 

Queria saber quais dias ele posta aula, alguem sabe me dizer?

**Comment by webkaiyo** [comment]
Olá, @Amir258! Eu posso estar errado, mas as lives são feitas a partir das 19:00.

**Comment by Amir258** [comment]
> 
> 
> Olá, @Amir258! Eu posso estar errado, mas as lives são feitas a partir das 19:00.



> 
> 
> Olá, @Amir258! Eu posso estar errado, mas as lives são feitas a partir das 19:00.

Sabe me dizer se é todos os dias?

**Comment by webkaiyo** [comment]
Olá, @Amir258! Acredito que não.

**Comment by Amir258** [comment]
> 
> 
> Olá, @Amir258! Acredito que não.

Certo, obrigado.
