### ISSUE TITLE
Teste-onde posso encontrar os slides da aula 04

### ISSUE THREAD

**Issue by JoaoNevoaCruz-81** [gustavoguanabara/git-github#129]
teste

**Comment by webkaiyo** [comment]
Olá, @JoaoNevoaCruz-81! [aula 04 do curso de Git e GitHub](https://youtu.be/gMh6lrXibWY) **não** possui slides, pois se trata de uma aula prática.

**Comment by JoaoNevoaCruz-81** [comment]
Hey, @webkaiyo obrigado!Era só uma teste de uma aula do curso de Git e Github.

**Comment by webkaiyo** [comment]
Olá, @JoaoNevoaCruz-81! Se foi apenas um teste, então fecha a issue.
