### ISSUE TITLE
Como acesso as versões anteriores do meu repositório?

### ISSUE THREAD

**Issue by solidade** [gustavoguanabara/git-github#1317]
Professor, tem alguma outra forma para acessar as versões anteriores do repositório? Até a aula que assisti mostrou apenas exibindo arquivos ocultos (a pasta .git), mas eu queria acessar isso diretamente do github desktop.

**Comment by lucasnogueiragomes** [comment]
Olá @solidade, não sou o professor mas creio que posso lhe ajudar. Para acessar as versões anteriores do seu repositório siga estes passos.
- Entre em seu perfil.
- Acesse o seu repositório.
- Escolha o arquivo do qual deseja ver as versões. 
- Clique no botão da parte superior direita do arquivo, chamado ´´History´´ (será outro nome se o seu site estiver em Português ou outro idioma).
Na imagem anexada eu mostro onde fica essa opção.
![github ajuda issue](https://user-images.githubusercontent.com/92893768/138789283-144d57d5-66c6-4cbb-a6a7-7fa6325df5a3.PNG)
.

**Comment by solidade** [comment]
@lucasnogueiragomes cara, muito obrigado!!! 
Super simples, mas eu tava batendo cabeça aqui para encontrar!
Salvou!
