### ISSUE TITLE
Game-2D-Colaborativo

### ISSUE THREAD

**Issue by odiegosilva1** [gustavoguanabara/git-github#132]
---
 
 Meu nome é @odiegosilva1 vou começar um projeto de game 2D, espero poder aprender e compartilhar conhecimentos. Farei **UPDATE** do repositório em breve.  Mais conteúdos falando sobre o game nos _links_ abaixo. 
---
   - MEUS CANAIS
     * [ PODCAST] - (https://open.spotify.com/show/3U0N3TSPqyBKlKaaL2CuhKrl)
     * [YOUTUBE] - (https://www.youtube.com/channel/UCe2YauKjdC7cGzQTXqGfcMw/videos)
     * [TWITTER]- (https://twitter.com/unopllayer)
---

**Comment by odiegosilva1** [comment]
Mudança título

**Comment by webkaiyo** [comment]
Olá, @odiegosilva1! A divulgação de seu perfil e seus projetos devem ser feitas na issue #3.
