### ISSUE TITLE
alguns slides das aulas estão faltando (Não so da aula 4 rsrs)

### ISSUE THREAD

**Issue by quelsonls** [gustavoguanabara/git-github#1329]
Tem aula 1,2,3, 10,11.

**Comment by quelsonls** [comment]
NAO TEM SLIDES , FOI APENAS TESTE . 

ESTOU ASSISTINDO O CURSO ATUAL 2021.

**Comment by leonardinobre** [comment]
No youtube tem a playlist completa. [Cliqueaqui](https://www.youtube.com/playlist?list=PLHz_AreHm4dm7ZULPAmadvNhH6vk9oNZA)
