### ISSUE TITLE
[DÚVIDA] Acesso negado para publicar um novo repositório

### ISSUE THREAD

**Issue by Joycekellyy** [gustavoguanabara/git-github#133]
Estou com uma dificuldade tremenda. Queria uma pequena ajudinha...
 

- Basicamente eu não estou conseguindo publicar meu primeiro repositório. O GitHub Desktop pede minha conta do GitHub e eu coloco os dados, logo em seguida aparece **Acesso negado**, como mostra na foto a seguir... Alguém poderia me dizer como posso resolver esse problema?

![Capturar](https://user-images.githubusercontent.com/63926941/79791567-e9555880-8323-11ea-8275-2659a377db51.PNG)

**Comment by webkaiyo** [comment]
Olá, @Joycekellyy! Você tem **certeza** que o repositório clonado pertence a sua conta? Ou que você logou na mesma conta que o repositório foi criado?

**Comment by Joycekellyy** [comment]
@webkaiyo, sim eu tenho certeza. Coloquei o email e a senha corretamente, o único motivo viável pra isso talvez seja que eu estou como **convidado** no computador, e não instalei o Git como administrador... Seria esse o problema?

**Comment by webkaiyo** [comment]
Olá, @Joycekellyy! Em qual pasta você está criando seu repositório? Já tentou executar o GitHub Desktop como administrador? Já tentou criar um repositório via comandos?

**Comment by Joycekellyy** [comment]
Olá @webkaiyo, estou criando uma pasta em usuário **convidado/Documentos**. Ainda não, vou tentar mais tarde e te darei retorno. Ainda não sei como utilizar comandos...  ┐(´ー｀)┌

**Comment by webkaiyo** [comment]
Olá, @Joycekellyy! Vou te dar um pequeno guia de como usar comandos em Git, você verá que não tem nada de difícil:

1. Abra o Prompt de Comando.

Para **clonar um repositório**, use:
```git
git clone <url do repositório>
```

2. Faça alterações no repositório.

Para **adicionar arquivos não-rastreados/não-estagiados**, use:
```git
git add *
```
`Nota:` isso adicionará **todos** os arquivos.

Para **fazer um commit**, use:
```git
git commit -m "Título do commit"
```

Para **fazer um push**, use:
```git
git push origin master
```
`Nota:` isso fará um push para a branch **master**.

Qualquer dúvida sobre os comandos é só falar.

**Comment by Joycekellyy** [comment]
AAAA SIIMMM MUITO OBRIGADA @webkaiyo !
Vou tentar e te dou retorno.  :3
