### ISSUE TITLE
O uso de Issue em projetos pessoais

### ISSUE THREAD

**Issue by fredsonchaves07** [gustavoguanabara/git-github#139]
E ai pessoal! Tudo tranquilo?

Gostaria de usar esse espaço para postar uma pequena dúvida em relação a issues :smiley:

Posso utilizar as issues em meus projetos pessoais? Ou seja, criar, por exemplo, uma issue que conterá um checklist das funcionalidades que o projeto vai ter? 

Grande abraço!
Parabéns @gustavoguanabara! pela iniciativa

**Comment by webkaiyo** [comment]
Olá, @fredsonchaves07! Não apenas pode como **é recomendado** você criar uma ou um grupo de issues (também chamados de [milestones](https://help.github.com/en/github/managing-your-work-on-github/about-milestones)), para manter a organização do seu projeto. Você, como dono do repositório, também pode criar issues para procurar soluções de problemas que nem você sabe resolver (estranho, não?).

**Comment by fredsonchaves07** [comment]
Entendi.
Na verdade queria usa-la para colocar um checklist das funcionalidades que já foram implantadas e/ou que ainda serão implantadas.

**Comment by webkaiyo** [comment]
Olá, @fredsonchaves07! Sim, você pode fazer isso tranquilamente.

**Comment by fredsonchaves07** [comment]
Show!!
Valeu pelos esclarecimentos!
