### ISSUE TITLE
Formatação de Tabelas com Markdown

### ISSUE THREAD

**Issue by fredsonchaves07** [gustavoguanabara/git-github#140]
Boa noite pessoal!

Uma pequena dúvida...

Eu consigo formatar tabelas usando Markdown? Ou seja, trabalhar com alinhamento, ajustes nas linhas e colunas.. Etc.

**Comment by webkaiyo** [comment]
Olá, @fredsonchaves07! Eu recomendo você ver [este](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet) repositório do `adam-p`, que explica muito bem (em inglês) como funciona tabelas em Markdown.

**Comment by fredsonchaves07** [comment]
Show!! Valeu man
