### ISSUE TITLE
Deletar pasta

### ISSUE THREAD

**Issue by ArthurFuchsReis** [gustavoguanabara/git-github#142]
Boa tarde Gustavo, como faço para deletar o meu repositório antigo?

Att,

@ArthurFuchsReis

**Comment by webkaiyo** [comment]
Olá, @ArthurFuchsReis! Você quer deletar seu repositório **local** ou seu repositório **remoto**?

**Comment by ArthurFuchsReis** [comment]
no caso ambos, pois tenho um que é desnecessário, que criei sem querer.

Obrigado @webkaiyo

**Comment by webkaiyo** [comment]
Olá, @ArthurFuchsReis! Para deletar seu repositório remoto, você pode seguir [este guia](https://help.github.com/en/github/administering-a-repository/deleting-a-repository). E para deletar seu repositório local, você pode:

1. Deletar a pasta raiz, ou
2. Deletar a pasta `.git` que está oculta dentro do seu repositório.

**Comment by ArthurFuchsReis** [comment]
Obrigado @webkaiyo . Vou fazer isso.

**Comment by m-sergio** [comment]
Valeu cara @webkaiyo! Tinha dificuldades para apagar um repositorio, mas com o guia que compartilhaste acabei conseguindo...
