### ISSUE TITLE
O curso acabou ?

### ISSUE THREAD

**Issue by edivancarvalho** [gustavoguanabara/git-github#143]
## Boa Noite a todos
---
O curso terminou??
Só uma observação de redes sociais só tenho 2 essa e linkedin.
Mas gostaria de saber que dia terá as demais aulas. Obrigado.

**Comment by webkaiyo** [comment]
Olá, @edivancarvalho! Por enquanto estamos sem notícias, mas tenho certeza que o curso não acabou!

**Comment by edivancarvalho** [comment]
## Obrigado
---

**Comment by edivancarvalho** [comment]
Oba o curso 
####  Voltou
----
