### ISSUE TITLE
Clonando Repositório

### ISSUE THREAD

**Issue by samillemachado** [gustavoguanabara/git-github#1431]
Oi pessoal! 😄 
Fiquei com uma dúvida sobre a clonagem: 
Clonei a pasta do curso. Quando essa pasta for atualizada pelo Guanabara, aqui no GitHub, ela vai ser atualizada pra mim quando eu der um Fetch no meu GitHub Desktop?  
Obrigada!

**Comment by RubenManuel24** [comment]
**não vai, porque a pasta que clonaste está somente no teu repositório local, e nem dá para mandares para o repositório remoto do dono original**

Muito obrigado pela tua colaboração!
![68747470733a2f2f36362e6d656469612e74756d626c722e636f6d2f65353435393561336463386364656330393436323462643765323961376461382f74756d626c725f6e3968666e71366e5247317461303769386f315f3530302e676966](https://user-images.githubusercontent.com/94210781/147999062-51612f27-4eb5-4cee-a195-4ecdc4a24f93.gif)


**Meus contactos:**
* Meu Whatsapp: +244 937692714
* Meu email: [Email](www.gemeorubensapalomanuel@gmail.com) 
* Meu perfil no Linkedin: [Linkedin](https://www.linkedin.com/in/ruben-manuel-22a412218/)

**Comment by samillemachado** [comment]
Ah, certo!
Obrigada!
