### ISSUE TITLE
Onde está os slides da aula 04?

### ISSUE THREAD

**Issue by jeffersonprocopio** [gustavoguanabara/git-github#1460]
Procurei os slides da aula 04 e não encontrei alguem poderia atualizar para mim?

**Comment by daniel0queiroz** [comment]
Também estou nessa aula do curso de github rs

**Comment by Fneumannt** [comment]
Estou na mesma aula kkkkk

**Comment by flaviomelo10** [comment]
Eu também!!

**Comment by DavydEdivaldo** [comment]
Cheguei nela agr kkkkk

**Comment by jacquelinewerner21** [comment]
tb

**Comment by Georgejcmp** [comment]
Boa tarde, A aula 04 do Curso de Git e GitHub não tem slides! Ela foi uma aula prática.
