### ISSUE TITLE
Problema na plataforma do Curso em Vídeo - Curso de Git e GitHub

### ISSUE THREAD

**Issue by KayanOkagawa** [gustavoguanabara/git-github#1463]
# Esse evento ao vivo não está mais disponível.

Bom dia, gostaria de saber se é só comigo ou mais alguém está com problema para visualizar os vídeos de **Git** e **GitHub**. Estou na ultima aula do curso e não consigo acessar os videos.

![Print do Site](https://user-images.githubusercontent.com/97108599/149623614-c3616793-3149-4663-969d-04ebc075b1c8.png)

@gustavoguanabara

**Comment by ghost** [comment]
@KayanOkagawa estava funcionando normal comigo por aqui, passei a tarde hoje assistindo.

**Comment by KayanOkagawa** [comment]
Bom dia, obrigado pela resposta @lucasrenandns . Isso que é estranho eu consigo assistir todos os outros cursos, porém só nesse ocorreu esse erro. Já limpei o cache do navegador e testei abrir em outro, mas o erro continua.

**Comment by lucasrenandns** [comment]
tenta ver se consegue encontrar a solução procurando pela internet
