### ISSUE TITLE
Teste Criar Issues

### ISSUE THREAD

**Issue by bsjamile** [gustavoguanabara/git-github#1468]
Testando 123

**Comment by bsjamile** [comment]
;) *-*

**Comment by bsjamile** [comment]
Não use a issue para falar sobre assuntos que não é da issue!

**Comment by bsjamile** [comment]
@gustavoguanabara é um professor muito maneiro!!

**Comment by bsjamile** [comment]
O ***curso não tem slide***
![O tao de Warren](https://user-images.githubusercontent.com/96315852/150550417-106c6c31-0770-4d9a-8fd7-d1bf63e31e2b.jpg)

**Comment by bsjamile** [comment]
*** negrito e itálico
** apenas negrito

**Comment by bsjamile** [comment]
uooooollll

Muito obrigada pela sua colaboração!

Me add no [Linkedin](https://www.linkedin.com/in/jamile-barroso/) também! :)

**Comment by EduardoGreve** [comment]
nome | idade | numero
--- | --- | ---
Eduardo | 22 | 01
Eduardo | 22 | 01
Eduardo | 22 | 01
