### ISSUE TITLE
Cadê os slides da aula 04?

### ISSUE THREAD

**Issue by CarolinoLeonardo** [gustavoguanabara/git-github#1479]
Criando este issue aqui só pra mostrar que aprendi e assisti sua aula sobre issues direitinho!! rsrss

**Comment by diegoferrosouza** [comment]
Respondendo só pra parecer que estou contrubuindo com a solução. Também to aprendendo.

**Comment by gitmattalves** [comment]
# Estou fazendo o curso de GitHub e testando

Testando __Markdown__

- [x] Curso html
- [x] Curso GitHub
- [ ] Curso css

Acessa [Aqui](https://github.com/gitmattalves) e tenha mais informações



![GitHub-Emblema](https://user-images.githubusercontent.com/89815246/152459127-3ece2a79-9be5-45b9-97d2-47d3734923a8.png)

Curso :100:  ssacional :star_struck: 
:1st_place_medal:

**Comment by CarolinoLeonardo** [comment]
Obrigado gente por comentarem aqui!!! Finalizei o curso de GIT e GitHub e comecei o de JavaScript.... vamo que vamo!
