### ISSUE TITLE
Onde estao os slides da aula 4?

### ISSUE THREAD

**Issue by tarikkadri** [gustavoguanabara/git-github#1496]
So testando aqui, desculpe rs.

**Comment by RodolfoGDS** [comment]
ainda procurando o slide da aula 4 @gustavoguanabara do curso de **Git-GitHub** disponível gratuitamente [diretamente clicando aqui](https://www.cursoemvideo.com/curso/curso-de-git-e-github/aulas/aulas-de-git-e-github/modulos/voce-sabe-usar-issues-curso-de-git-e-github/) e ainda nos ensinou a colocar uma imagem na issues
![homercat](https://user-images.githubusercontent.com/75094857/154138875-c590b62d-fe07-4bc6-89c3-63f7ec8e93d7.png)
s
