### ISSUE TITLE
onde estão os slides da aula 004

### ISSUE THREAD

**Issue by claudionormax** [gustavoguanabara/git-github#1516]
procurei e não foram encontrados !! alguém poderia me ajudar !!

**Comment by lucasxgb** [comment]
Olá amigo! Como nosso querido professor guanabara explicou em live, a aula 4 não possue slides, pois, foi uma aula pratica do curso de **Git e Github**, que pode ser acessado [diretamente clicando aqui](https://youtu.be/xEKo29OWILE)
![guana6](https://user-images.githubusercontent.com/68016822/156032315-74da73d6-b907-426a-b7aa-acd040f47810.png)

**Comment by claudionormax** [comment]
> Olá amigo! Como nosso querido professor guanabara explicou em live, a aula 4 não possue slides, pois, foi uma aula pratica do curso de **Git e Github**, que pode ser acessado [diretamente clicando aqui](https://youtu.be/xEKo29OWILE) ![guana6](https://user-images.githubusercontent.com/68016822/156032315-74da73d6-b907-426a-b7aa-acd040f47810.png)

muitíssimo obrigado @lucasxgb !! estou realmente exercitando !!
