### ISSUE TITLE
Testando a linguagem Markdown ❎

### ISSUE THREAD

**Issue by lucasxgb** [gustavoguanabara/git-github#1532]
Vamos testar a linguagem aqui!

**Comment by lucasxgb** [comment]
# Aprendendo Markdown

Estou aprendendo linguagem **Markdown** no Curso em Vídeo de *Git e GitHub*
-

Podemos misturar configurações, como:
__*Negrito & Italico*__



# Listas:


Lista numerada: 
1. Teste
2. Teste2
   2.1 Teste3
3. Teste 4 

Lista demarcada:
* Teste 
* Teste
* Teste
   * Teste3.1

Lista de Tarefas:

- [ ] Criar a página principal
- [ ] Criar a página da loja
- [ ] Finalizar runião com o cliente
   - [X] Finalizar aula de markdown



![github-163-761603](https://user-images.githubusercontent.com/68016822/156225123-96ec64c3-d277-4ffb-83a5-9768699bca55.png)

[Acesse meu GitHub](github.com/lucasxgb)

**Comment by lucasxgb** [comment]
# Tabelas

Num | Nome | Nota 
---|---|---
1 | Guana | 7,6
2 | Gabriel | 8
3 | Mari | 9

Terminou a tabela!

**Comment by lucasxgb** [comment]
Não entendo direito para que serve o comando  `documente.getElementById()` da linguagem JavaScript 
**(Basta colocar entre crase ( ` ), para identificar que se trata de um comando)**
---

# Programa em Py

```
num = int(input('Digite um valor:'))
if num % 2==0:
    print('O valor {} é PAR'.format(num))
else
    print('O valor {} é Impar'.format(num))
```

**Comment by lucasxgb** [comment]
Olá, Gafanhoto 🖖🏾

**Comment by lucasxgb** [comment]
> ## Não entendo direito para que serve o comando `documente.getElementById()` da linguagem JavaScript
> **(Basta colocar entre crase ( ` ), para identificar que se trata de um comando)**
> # Programa em Py
> ```
> num = int(input('Digite um valor:'))
> if num % 2==0:
>     print('O valor {} é PAR'.format(num))
> else
>     print('O valor {} é Impar'.format(num))
> ```

👍🏾

**Comment by Jeter-S** [comment]
Estou aprendendo linguagem **Markdown**  no curso em videos Git & GitHub

# Aula de linguagem Markdown!
---
podemos _*misturar*_ configurações (negrito e italico)
---

Lista numerada:

1. teste
2. teste2
   3. teste3

Lista demarcada: 

* testes
* teste
   * teste

Lista de tarefas:
- [ ] criar pagina principal.
- [x] criar pagina da loja.
- [ ] pagamento.
---

Num | Nome | Nota
---|---|---
1 | Jéter | 10,0
2 | Luiza | 9,7
3 | Suzana | 8,3
Fim da tabela!
---

Ainda estou meio perdido com os as classes de `model` no java

Testando 
```
system.out.println ("Hello World");
```

emojis 💯 🖖🏾 

[ GitHub dos emojis ](https:ikatiang.github.io)

[ Acesse meu GitHub ](https://Jeter-S.github.io)

**Comment by lucasxgb** [comment]
> Estou aprendendo linguagem **Markdown** no curso em videos Git & GitHub
> 
> # Aula de linguagem Markdown!
> ## podemos __misturar__ configurações (negrito e italico)
> Lista numerada:
> 
> 1. teste
> 2. teste2
>    3. teste3
> 
> Lista demarcada:
> 
> * testes
> * teste
>   
>   * teste
> 
> Lista de tarefas:
> 
> * [ ]  criar pagina principal.
> * [x]  criar pagina da loja.
> * [ ]  pagamento.
> 
> Num	Nome	Nota
> 1	Jéter	10,0
> 2	Luiza	9,7
> 3	Suzana	8,3
> Fim da tabela!		
> Ainda estou meio perdido com os as classes de `model` no java
> 
> Testando
> 
> ```
> system.out.println ("Hello World");
> ```
> 
> emojis 💯 🖖🏾
> 
> [ GitHub dos emojis ](https:ikatiang.github.io)
> 
> [ Acesse meu GitHub ](https://Jeter-S.github.io)
Boa!  💯

**Comment by lucasxgb** [comment]
> Estou aprendendo linguagem **Markdown** no curso em videos Git & GitHub
> 
> # Aula de linguagem Markdown!
> ## podemos __misturar__ configurações (negrito e italico)
> Lista numerada:
> 
> 1. teste
> 2. teste2
>    3. teste3
> 
> Lista demarcada:
> 
> * testes
> * teste
>   
>   * teste
> 
> Lista de tarefas:
> 
> * [ ]  criar pagina principal.
> * [x]  criar pagina da loja.
> * [ ]  pagamento.
> 
> Num	Nome	Nota
> 1	Jéter	10,0
> 2	Luiza	9,7
> 3	Suzana	8,3
> Fim da tabela!		
> Ainda estou meio perdido com os as classes de `model` no java
> 
> Testando
> 
> ```
> system.out.println ("Hello World");
> ```
> 
> emojis 💯 🖖🏾
> 
> [ GitHub dos emojis ](https:ikatiang.github.io)
> 
> [ Acesse meu GitHub ](https://Jeter-S.github.io)

Nice!  💯
