### ISSUE TITLE
Onde está os slides da Aula 04? (Testando a criação de uma issues)

### ISSUE THREAD

**Issue by VitorEMSB** [gustavoguanabara/git-github#1533]
Procurei os slides da aula 04 e não encontrei. Alguém poderia atualizar para min?

**Comment by VitorEMSB** [comment]
Testando resposta de issues.

**Comment by VitorEMSB** [comment]
**Testando link**: [Clique aqui](https://www.youtube.com/watch?v=xEKo29OWILE&list=PLHz_AreHm4dm7ZULPAmadvNhH6vk9oNZA
![78839356-b67b9e00-79ce-11ea-93ff-9f97de8f2c8f](https://user-images.githubusercontent.com/69357785/156273150-9b3831ff-68d3-4731-92f9-6804eb60c79b.png)

**Comment by VitorEMSB** [comment]
Divulgações estão ocorrendo na issue de número #3

**Comment by ghost** [comment]
29/03/2022

**Comment by LidianeMendess** [comment]
24/04/2022
