### ISSUE TITLE
Conflito de merge

### ISSUE THREAD

**Issue by beatrizflorenccio** [gustavoguanabara/git-github#154]
Olá, professor. Eu tenho uma organização aqui no GitHub. Meus colegas de equipe estão na organização. 

Nós tentamos fazer modificações num mesmo arquivo de um repositório, mas como imaginávamos, não conseguimos enviar essas modificações aqui para o repositório remoto, pois deu um erro de conflito. Conflito de merge de diferentes alterações.

Tem alguma maneira de eu resolver esse conflito? Se nós mexermos no branch, talvez... poderíamos conseguir modificar o mesmo arquivo simultaneamente?

Por favor, peço que nos ajude.
Abraços!

**Comment by OzneKx** [comment]
Olá, Beatriz!

Conflitos "merge" no GitHub podem ser resolvidos se forem causados por diferentes alterações em mesmas linhas em uma mesma file em branches diferentes de seu repositório GIT.

Procure o repositório que esteja com o conflito merge e abra o editor de texto, logo em seguida, procre marcadores de conflitos " <<<<<<< " . O sinal " ======= " divide as suas mudanças para com as mudanças de outros usuários, que segue " >>>>>>> BRANCH-NOME ".

Confesso que sou leigo ainda, me perdoe, mas estou aprendendo! Confira na íntegra, caso queira nesses links:

- https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/resolving-a-merge-conflict-on-github
- https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/resolving-a-merge-conflict-using-the-command-line

**Comment by beatrizflorenccio** [comment]
Muito obrigada, amigo! Me ajudou, resolvi o conflito. Mas gostaria de saber também se existe uma maneira de evitar esses conflitos para que eu conseguisse trabalhar efetivamente com a minha equipe. Sabe de algo?

**Comment by OzneKx** [comment]
O máximo que eu posso indicar, no momento, é o curso ao vivo que está rolando neste exato momento. Segue o link:

https://www.youtube.com/watch?v=xAOBQtSVI_k

**Comment by beatrizflorenccio** [comment]
Eu assisti a aula! Me ajudou a entender e pensar numa solução. Obrigada!
