### ISSUE TITLE
Começando depois dos 56...

### ISSUE THREAD

**Issue by profantoniobezerra** [gustavoguanabara/git-github#1556]
Olá povo...sou o Antonio, tenho agora 58 anos, começei a estudar desenvolvimento web no ano passado, sempre fui um apaixonado pela área, Sou graduado em artes visuais, tarbalho como fotógrafo, prof de artes e etc...por enquanto não tenho nunhum projeto, mas fiz vários cursos do Guanabara, do Pronatec e agora  fazendo Ciencias da computação  na Universidade Livre....

Será que posso ser um Dev ainda????

**Comment by lucasrenandns** [comment]
@profantoniobezerra, com certeza! a tempo para todas as coisas, e tudo podemos naquele que nos fortalece. Não desista e forte abraço! :+1:
