### ISSUE TITLE
Testando > Onde está os slides da aula 04?

### ISSUE THREAD

**Issue by lucasc-costa** [gustavoguanabara/git-github#156]
Procurei os slides da aula 4 e não encontrei. Alguém poderia atualizar para mim?

**Comment by ValencaBruno** [comment]
Procure os slides da aula 4 e não encontre. Alguém poderia atualizar para mim?

**Comment by Eleson-Souza** [comment]
@lucasc-costa, não existe slide da aula 04, a aula foi prática!

**Comment by lucasplucena** [comment]
@Eleson-Souza , acho que o @lucasc-costa se referiu à aula das issues nesse post 😄

**Comment by jccesar22** [comment]
kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk
