### ISSUE TITLE
Slides da Aula 4

### ISSUE THREAD

**Issue by lecooliveirastartdev** [gustavoguanabara/git-github#1562]
Teste de inserção de issues.

**Comment by PedroHenriqueSSantana** [comment]
testando issues

**Comment by ihenriquebr** [comment]
.

**Comment by ihenriquebr** [comment]
[clique aqui](https://www.youtube.com/watch?v=mUZOySyVcuQ&list=PLHz_AreHm4dm7ZULPAmadvNhH6vk9oNZA&index=9)

**Comment by lecooliveirastartdev** [comment]
> Teste de inserção de issues.
