### ISSUE TITLE
E os slides da aula 04 professor?

### ISSUE THREAD

**Issue by LuisItalo** [gustavoguanabara/git-github#1629]
Não encontrei os slides da aula, alguém poderia colocar os slides?

**Comment by CLAUDEMIRMARTINSFERRAZ** [comment]
Caro Sr. @LuisItalo . A aula 04 do Curso de GIT e GitHub  não tem slides!! Ela foi uma aula pratica que você pode acessar
 [ Você pode acessar diretamente, clicando aqui ](https://www.youtube.com/playlist?list=PLHz_AreHm4dm7ZULPAmadvNhH6vk9oNZA)
