### ISSUE TITLE
Como atualizar um projeto clonado?

### ISSUE THREAD

**Issue by profaramis** [gustavoguanabara/git-github#164]
Olá Prof. Gustavo... Você poderia me dizer como faço para atualizar os projetos clonados do git hub? Você na aula de clonagem, deu o exemplo para clonarmos o seu progeto de html5 eu fiz isso, só que no dia que clonei tinha, por exemplo, 6 pdfs de aula, Hj já são 13. Como faço para fazer a clonagem desses que ainda não tinham da epoca da clonagem para dentro do meu computador?

**Comment by ghost** [comment]
Olá, @profaramis! Veja se [esse](https://webkul.com/blog/syncing-local-repository-with-remote-repository-on-github/amp/) artigo pode lhe ajudar a sincronizar repositórios.

**Comment by profaramis** [comment]
> Olá, @profaramis! Veja se [esse](https://webkul.com/blog/syncing-local-repository-with-remote-repository-on-github/amp/) artigo pode lhe ajudar a sincronizar repositórios.

Muito obrigado meu amigo!
