### ISSUE TITLE
Onde está os slides da Aula 04?

### ISSUE THREAD

**Issue by felipe220583** [gustavoguanabara/git-github#1697]
Procurei os slides da aula e não encontrei. Alguém poderia atualizar para mim?

**Comment by felipe220583** [comment]
Caro @felipe220583 a aula 4 do curso de Git e GitHub não tem slides. Ela foi uma aula prática que você pode acessar através  do link  [https://youtu.be/mUZOySyVcuQ]
![Mr_bean](https://user-images.githubusercontent.com/83296062/171055257-272f886d-22ff-437c-b128-18f454b2bbfb.jpg)

Obrigado
Dinada

**Comment by robsonpfcel** [comment]
OK!!
