### ISSUE TITLE
Onde está os slides da Aula 04?

### ISSUE THREAD

**Issue by ramoncpb** [gustavoguanabara/git-github#1736]
Pooxa Guanabara, estamos em 2022 e eu ainda procurando os slides da aula 04! Alguém atualiza para mim?

**Comment by Vidal-Gus** [comment]
Estamos na mesma situação então meu caro!!

**Comment by pedromagnorodrigues** [comment]
Caro @ramoncpb e @Vidal-Gus a aula 4 não tem slides, pois foi uma aula prática de como abrir uma issue. Dica: Assistir a aula 9 ([Você sabe usar Issues? – Curso de Git e [GitHub]()](https://www.cursoemvideo.com/curso/curso-de-git-e-github/aulas/aulas-de-git-e-github/modulos/voce-sabe-usar-issues-curso-de-git-e-github/)
