### ISSUE TITLE
Slides da aula 4? 

### ISSUE THREAD

**Issue by ghost** [gustavoguanabara/git-github#1737]
Boa noite,
Não encontrei os slides da aula 4!

**Comment by pedromagnorodrigues** [comment]
Caro @edumarcon a aula 4 não tem slides, pois foi uma aula prática de como abrir uma issue. Dica: Assistir a aula 9 ([Você sabe usar Issues? – Curso de Git e GitHub](https://www.cursoemvideo.com/curso/curso-de-git-e-github/aulas/aulas-de-git-e-github/modulos/voce-sabe-usar-issues-curso-de-git-e-github/)
