### ISSUE TITLE
Onde os slides da aula 04?

### ISSUE THREAD

**Issue by fhferreir** [gustavoguanabara/git-github#1748]
Procurei os slides da aula 04 e não encontrei. Alguém poderia atualizar pra mim?

**Comment by BellaMartinsSilva** [comment]
@fhferreir 
O professor falou na aula 9 que não tem slides da aula 4, pois foi uma aula prática.
Espero ter ajudado.

**Comment by fhferreir** [comment]
Obrigado @BellaMartinsSilva ! Ajudou sim!
