### ISSUE TITLE
 Problema na resolução de exercício de algoritmos do Estudonauta

### ISSUE THREAD

**Issue by ronan-jordao** [gustavoguanabara/git-github#177]
Estou enfrentando um problema na resolução de exercício de algoritmo  do Estudonauta.O objetivo do exercício é cadastrar pessoas com seu nome,sexo e idade e na saída de dados tem que mostrar:

*Nome e idade da mulher mais jovem .
*Nome e idade da mulher mais velha .
*Nome e idade do homem mais jovem .
*Nome e idade do homem mais velho.

**Obs 1**:No meu programa ao cadastrar 3 homens e 2 mulheres.Não mostra o nome e a idade da mulher mais jovem.
**Obs 2**:Até na resolução do @gustavoguanabara  tinha um erro semelhante.No vídeo 7,módulo 3.
**Obs 3**:Antes de vim aqui pedir ajuda de resolução.Eu tentei muito.De várias maneiras.Umas 4 horas tentando solucionar 100% o programa.
**Obs 4**:Eu sei que posso fazer a pergunta no fórum do Estudonauta.Mas por lá demora alguns dias.Acredito que aqui a meu pedido de ajuda terá maior visibilidade e assim alguém apto poderá responder.

*Código:*

´programa
{
	
	funcao inicio()
	{
		inteiro cont = 1 , 
			   num_pessoa , 
			   idade,
			   idade_homem_jovem = 0,
			   idade_homem_velho = 0,
			   idade_mulher_jovem = 0,
			   idade_mulher_velha = 0
		cadeia nome , 
			  nome_homem_jovem = "", 
			  nome_homem_velho = "", 
			  nome_mulher_jovem= "" ,
			  nome_mulher_velha= "" 
		caracter sexo
		
		escreva("{Exercício 38 - Analisando idades}\n\n")

		escreva("Quantas pessoas você deseja cadastrar? ")
		leia(num_pessoa)

		enquanto(cont <= num_pessoa){
			escreva("============================= \n")
			escreva("     ",cont,"º Cadastro       \n")
			escreva("============================= \n")
			escreva("Nome: ")
			leia(nome)
			escreva("Sexo: ")
			leia(sexo)
			escreva("Idade: ")
			leia(idade)

			
			se(cont == 1){
				//Homens
				se(sexo == 'm' ou  sexo == 'M' e idade_homem_jovem == 0){
					nome_homem_jovem = nome
					idade_homem_jovem = idade
					nome_homem_velho = nome
					idade_homem_velho = idade
				}
				//Mulheres
				se(sexo == 'f' ou  sexo == 'F' e idade_mulher_jovem == 0){
					nome_mulher_jovem = nome
					idade_mulher_jovem = idade
					nome_mulher_velha = nome
					idade_mulher_velha = idade
				}
			}senao{
				//Homens
				se(sexo == 'M' ou sexo == 'm' e idade > idade_homem_velho){
					nome_homem_velho = nome
					idade_homem_velho = idade
				}
				se(sexo == 'M' ou sexo == 'm' e idade < idade_homem_jovem){
					nome_homem_jovem = nome
					idade_homem_jovem = idade
				}
				//Mulheres
				se(sexo == 'F' ou sexo == 'f' e idade > idade_mulher_velha){
					nome_mulher_velha = nome
					idade_mulher_velha = idade
				}
				se(sexo == 'F' ou sexo == 'f' e idade < idade_mulher_jovem){
					nome_mulher_jovem = nome
					idade_mulher_jovem = idade
				}
			
			}
			cont++
		}

		escreva("----------------------------------------------\n")
		escreva("[Mulheres]\n")
		escreva("A mulher mais jovem é a ",nome_mulher_jovem," que tem ",idade_mulher_jovem," anos.\n") //Aqui ocorre o erro
		escreva("A mulher mais velha é a ",nome_mulher_velha," que tem ",idade_mulher_velha," anos.\n")
		escreva("----------------------------------------------\n")
		escreva("[Homens]\n")
		escreva("O homem mais jovem é o ",nome_homem_jovem," que tem ",idade_homem_jovem," anos.\n")
		escreva("O homem mais velho é o ",nome_homem_velho," que tem ",idade_homem_velho," anos.\n")
		
	}`

*Entrada de Dados:*

{Exercício 38 - Analisando idades}

Quantas pessoas você deseja cadastrar? 6

1º Cadastro       
Nome: Ian
Sexo: m
Idade: 14
 
     2º Cadastro       
Nome: Ronan
Sexo: m
Idade: 24

     3º Cadastro       
Nome: Rana
Sexo: f
Idade: 19

     4º Cadastro       
Nome: Rayan 
Sexo: m
Idade: 15

     5º Cadastro       
Nome: Suliane
Sexo: f
Idade: 23

     6º Cadastro       
Nome: Welligton
Sexo: m
Idade: 22

**Saída de Dados:**
[Mulheres]
**A mulher mais jovem é a  que tem 0 anos.** //Aqui está o erro
A mulher mais velha é a Suliane que tem 23 anos.

[Homens]
O homem mais jovem é o Ian que tem 14 anos.
O homem mais velho é o Ronan que tem 24 anos.

**Comment by Felipe-Santos97** [comment]
Boa noite @ronan-jordao, eu também fiz esse curso ele me ajudou muito.
**Vamos entender esse problema**.

* Bom na linha 37 tem um desvio **SE**, ele pergunta se o contador é igual a 1.
* Se for igual a 1 ele entra no bloco e pergunta PRIMEIRO se é do sexo **Masculino** e em seguida pergunta se é **feminino**
* Vamos supor que seja **M** , Bom ele é o primeiro **do sexo Masculino** a ser cadastrado então tecnicamente ele é o mais jovem e o mais velho. 
*  Depois de verificar SE é do sexo M (linha 39) ele pergunta se é do sexo **F** (***linha 46***). Bom quem foi cadastrado foi do **sexo M** então ele não entra nesse bloco e sai do DESVIO.
* Apos sair do desvio ele NÃO executa o bloco do **SENÃO** (linha 52) E chega no final do primeiro loop.
* O **problema esta aqui**, pois no segundo loop o contador não vale mais 1, e ele nao executa o bloco do SE. Com isso o programa não consegue verificar a primeira do sexo F no caso, pois nunca mais o contador vai valer 1
* Como no caso o primeiro foi do sexo M e no segundo loop o contador vale 2 o programa não consegue saber quem foi a primeira mulher e não consegue atribuir que a primeira mulher cadastrada seja a mais nova e a mais velha.


**Sugestão**
* Faça cada volta do loop verificar o sexo da pessoa, e se é a primeira a ser cadastrada do sexo correspondente.
* No seu exemplo só era feita uma vez essa verificação, por conta do teste logico **se(cont == 1)** 


* Veja no meu exemplo (as variaveis estão com nome diferentes)
``` 
programa
{
 	
	funcao inicio()
	{
          inteiro laco = 1, cadastro, idade , totf = 0 , totm = 0 , jovem = 0 , velho = 0 , novinha = 0 , coroa = 0
          cadeia nome , homen_jovem = " ", homen_velho = " ", nome_coroa = " ", nome_novinha = " " 
          caracter sexo
          
             	      
		escreva("        CADASTRO DE PESSOAS      \n")
		escreva("=================================\n ")
		escreva(" Digite quantas pessoas: ")
		leia(cadastro)
		//LENDO OS DADOS
		enquanto(laco <= cadastro){
			escreva("----------------------------------\n ")
			escreva(laco ,"*PESSOA ")
			escreva("NOME: ")
			leia(nome)
			escreva("SEXO [M/F]: ")
			leia(sexo)
			escreva("IDADE: ")
			leia(idade)
			// calculando quantos M e F
			 se (sexo == 'm' ou sexo == 'M' ){
			 	totm++
			 	se (jovem == 0 ){
			 		jovem = idade
			 		velho = idade
			 		homen_jovem = nome
			 		homen_velho = nome
			 					 					 		
			 	}
			 	   se(idade < jovem ){
			 	  	jovem = idade 
			 	  	homen_jovem = nome
			 	  }
			 	  senao se (idade > velho  ){
			 	  	velho = idade 
			 	  	homen_velho = nome
			 	  }			 	
			 }
			 se (sexo == 'F' ou sexo == 'f' ){
			 	totf++
			 	se (novinha == 0 ){
			 		novinha = idade
			 		coroa = idade
			 		nome_novinha = nome
			 		nome_coroa = nome
			 		
			 					 					 		
			 	}
			 	   se(idade < novinha ){
			 	  	novinha = idade 
			 	  	nome_novinha = nome
			 	  }
			 	  senao se (idade > coroa  ){
			 	  	coroa = idade 
			 	  	nome_coroa = nome
			 	  }			 	
			 }

			
		laco++	
		} // Fim do enquanto


		escreva("==============================================================================\n ")
		escreva("Ao todo tivemos  ", totm , " homens e " , totf , " de mulheres cadastrados. \n" )
		escreva("O homen mais novo é ", homen_jovem , " que tem  " , jovem , " anos. \n" )
		escreva("O homen mais velho é  " ,homen_velho ,  " que tem  " , velho , " anos. \n" )
		escreva("A mulher mais nova é a ", nome_novinha , " que tem  " , novinha , " anos. \n" )
		escreva("A mulher mais velha é a ", nome_coroa , " que tem  " , coroa , " anos. \n" )
		
		escreva("===============================================================================\n\n ")		
 
	}
}
```
**Espero ter ajudado !**

**Comment by ronan-jordao** [comment]
Obrigado @Felipe-Santos97.Assim que for possível irei testar a sua sugestão. :+1:

**Comment by ronan-jordao** [comment]
@Felipe-Santos97 muito obrigado.Graças a sua sugestão eu conseguir resolver o problema.E mais do que isso eu consegui entender.Fazendo na prática parte por parte. :+1: 

Mas tenho uma dúvida.Tentei simplifica a sua lógica.Inserindo **Se,senao se e senao**.A principio parecia funcionar corretamente com poucas pessoas cadastradas.Mas cadastrando 20 pessoas surgiu um erro.Por exemplo :cadastrando 20 pessoas entre homens e mulheres.No resultado final registrou o 2º homem mais jovem como a primeiro mais jovem.Se puder me explicar porque só com os  **se's** independentes como você sugeriu o programa funciona de forma integral.E a minha lógica não funciona totalmente.Eu agradeceria muito.Falta apenas isso pra entender 100% a lógica.

Trecho de código:
```
se(sexo == 'M' ou sexo == 'm'){
		se(idade_homem_jovem == 0){
			idade_homem_jovem = idade
			idade_homem_velho = idade
			nome_homem_jovem = nome
			nome_homem_velho = nome
		}senao se(idade > idade_homem_velho){
			nome_homem_velho = nome
			idade_homem_velho = idade
		}senao{
			nome_homem_jovem = nome
			idade_homem_jovem = idade
		}
}
```

**Comment by Felipe-Santos97** [comment]
@ronan-jordao que bom que conseguiu resolver o exercício e entender a lógica, afinal é tendo duvidas que se aprende.
Então eu testei o meu exemplo com 20 pessoas e funcionou, tenta ver se o problema é com os **Se,senao se e senao** que vc adicionou.Pode ser que o ultimo **senão** (que testa a idade mais nova) não esteja indentado  com o da idade mais velha. 

 Manda o seu programa com as alterações ou o link do repositório.

**Comment by ronan-jordao** [comment]
@Felipe-Santos97  o meu programa já está funcionando corretamente com a sua lógica sugerida.Só com que a minha tentatica de simplificar a lógica (Se,senao se e senao) que deu o erro relatado acima.

Está aqui  o link do programa: [Programa Resolvido](https://github.com/ronan-jordao/Estudonauta/blob/master/1-Algoritmos%20(Portugol%20Studio)/M%C3%B3dulo%203-Estruturas%20de%20Repeti%C3%A7%C3%A3o/Aula%207-Maior%20e%20menor/Exercicio%2038-Analisando%20idades.por)

É basicamente o mesmo programa que você desenvolveu.Mas com variaveis diferentes.

Valeu.Muito Obrigado :+1: 

Irei fechar a issue daqui a pouco

Queria bater um papo contigo sobre programação.Ter um contato se for possivel e se você querer claro.Você parece ser um bom entendedor dessa área.

**Comment by Felipe-Santos97** [comment]
@ronan-jordao valeu, estudei programação la no estudonauta assim como vc.
Vou te seguir aqui, quando quiser só chamar, vlw.
