### ISSUE TITLE
Onde estão os slides da aula 04?

### ISSUE THREAD

**Issue by barbosawf** [gustavoguanabara/git-github#1794]
Por gentileza, professor!

Poderia disponibilizar os supostos slides da aula 04. Mas estou querendo mesmo é o mundo 4 e 5 do python.

**Comment by Saandronunes** [comment]
Também quero saber kkk

**Comment by matheushenriquemoreira** [comment]
**yf6ffffd**

**Comment by TiConsultor** [comment]
Rapaz, quem souber morre! kkkk

**Comment by barbosawf** [comment]
Issue closed!

**Comment by UellingtonLim4** [comment]
Onde está?

**Comment by luciofs** [comment]
Também estou a procura.
