### ISSUE TITLE
Problemas para mostrar o site com as edições

### ISSUE THREAD

**Issue by CarlosHenriqueLopes** [gustavoguanabara/git-github#1803]
Quando faço a pagina do site do projeto Android, ele aparece sem as definições criadas pelo arquivo CSS, por algum motivo ele mostra tudo, menos o que esta no .css criado no vscode.
Já coloquei todo o caminho das pastas quando o arquivo está na pasta, e sem pasta também, mesmo assim não aparece.

(O site está aparecendo sem as edições que estão no arquivo .css)

**Comment by SilasRodrigues19** [comment]
Respondi lá na issue do repositório de html-css nesse [link](https://github.com/gustavoguanabara/html-css/issues/256), mas vou responder aqui também porque pode ser a dúvida de mais alguém.

O arquivo está só com a extensão ".css" precisa dar um nome, como por exemplo: "style.css" e alterar o href do link no HTML também
