### ISSUE TITLE
Como apagar uma issue?

### ISSUE THREAD

**Issue by Luke02su** [gustavoguanabara/git-github#1822]
Divulguei o meu perfil no lugar errado. Gostaria de saber se é possível apagar uma issue.
Obrigado!

**Comment by Luke02su** [comment]
Descobri que somente o dono do repositório pode excluir. :)

**Comment by daniloprogramador93** [comment]
@Luke02su  estranho isso, se agente fez uma issue não pode apagar,
tava querendo também apagar ums repositórios para organizar meu github e não consegui
