### ISSUE TITLE
Onde esta o slide da aula 4? 

### ISSUE THREAD

**Issue by ThomsonLopes** [gustavoguanabara/git-github#1856]
Procurei os slide da aula 4 e nao encontro, alguém poderia atualizar para mim?

**Comment by WillianROM** [comment]
Eu pensei que esse era o issue que o professor criou na aula. hahahaha

**Comment by WillianROM** [comment]
Foi uma aula prática, então não tem slides.

**Comment by ThomsonLopes** [comment]
tava só testando mesmo KKKKKK
