### ISSUE TITLE
Alguem encontrou os slides da aula 4? 

### ISSUE THREAD

**Issue by ThProgrammer** [gustavoguanabara/git-github#1870]
Ando procurando os slides da aula 4 e não encontrei, alguém mais teve dificuldade de achar?

**Comment by WalleFerraz** [comment]
Olá ThProgrammer, a aula 04 não possui slides. Aqui está o link da videoaula: [Aula 04](https://github.com/gustavoguanabara/git-github/issues/5#issuecomment-611226237)
