### ISSUE TITLE
onde está os slides da aula 04?

### ISSUE THREAD

**Issue by kalebzaki4** [gustavoguanabara/git-github#1880]
onde está os slides da aula 04?

**Comment by leandroclv** [comment]
Acabei de ver essa aula e não pude testar no #5 pq o Guanabara fechou. Estou aprendendo a responder com o seu issue. Obrigado e desculpe o incômodo.

**Comment by marcioluizz** [comment]
Olá galera, depois de muito tempo estou comentando essa issue. Estou só aprendendo.

**Comment by kalebzaki4** [comment]
GG
