### ISSUE TITLE
onde está o slide da aula 4? 

### ISSUE THREAD

**Issue by EmessonPinheiro** [gustavoguanabara/git-github#1983]
teste de criação de nova issue

**Comment by EmessonPinheiro** [comment]
[a vida é dura](https://www.youtube.com/watch?v=mUZOySyVcuQ&list=PLHz_AreHm4dm7ZULPAmadvNhH6vk9oNZA&index=9
)

**Comment by Rodrigo-Vasconcellos** [comment]
ola, teste!!!!
