### ISSUE TITLE
Arquivos do Curso de Java

### ISSUE THREAD

**Issue by IncognitaDev** [gustavoguanabara/git-github#21]
Gostaria de pedir o upload dos arquivos do curso de Java do Curso em Vídeo

**Comment by gustavoguanabara** [comment]
No curso de Java tinha algum tipo de arquivo que eu prometi colocar???

**Comment by IncognitaDev** [comment]
No curso de Java são usados icons nós exercícios, como é um pouco difícil de encontrar icons do tamanho certo, gostaria que disponibilizasse, se não tiver agradeço da mesma forma.
