### ISSUE TITLE
Cadê a issue do gafanhoto perguntando onde estão os slides da aula 04?

### ISSUE THREAD

**Issue by ferreirageison** [gustavoguanabara/git-github#2155]
Procurei e não achei a issue do gafanhoto perguntando sobre os slides da aula 04.

Então, onde estão os slides da aula 04? Onde? Onde?

E onde está o gafanhoto?

**Comment by ghost** [comment]
Eu procurei e também não encontrei provavelmente deve ser uma Issue que já foi fechada então acredito que não aparecerá, eu estou fazendo o curso em 2023 e para mim também não consta... Espero ter ajudado.

**Comment by rafaelmstorres** [comment]
Encontrei a issue original [clique aqui](https://github.com/gustavoguanabara/git-github/issues/5) para acessar.
