### ISSUE TITLE
Como apago um repositorio.

### ISSUE THREAD

**Issue by FreakPy** [gustavoguanabara/git-github#2173]
Criei um repositorio particular e quero excluir ele do github qual é o caminho para isso.

**Comment by mohammadfaizalabdul** [comment]
Boa noite, bom eu deparei com o mesmo problema e solucionei ele de uma forma muito simples. Fui ao GitHub Desktop e selecionei o repositório que pretendia excluir e usei o atalho Ctrl+Backspace. De forma pratica tu só selecionas o repositório que pretendes eliminar e na aba de cima vai a opção repository e na terceira opção "Remove" clique ai e ele eliminará o repositório. Obrigado espero ter ajudado..

**Comment by mohammadfaizalabdul** [comment]
Oh e não estranhe o Boa noite kkkkk, é que na minha cidade já é noite, estou em Moçambique

**Comment by walterhenrique** [comment]
Entre no repositório e escolha a engrenagem de configurações (SETTINGS em inglês).
Role tudo para baixo e você encontrará uma área em cor diferente. Lá tem a opção de excluir seu repositório.
Será necessário informar a senha e confirmar uma frase que o sistema pedir.
Não há lixeira! Remover um repositório excluirá ele definitivamente!
Ahh, mais uma coisa. Todo o seu histórico de edição também é deletado. Logo, se você possuir vários quadradinhos verdes indicando sua atividade no GitHub e eles forem atividade deste repositório que você está excluindo, adeus - eles somem também.

Espero ter ajudado. Se resolver, não esquece de fechar esta ISSUE ^_^

![imagem_2023-01-12_165047116](https://user-images.githubusercontent.com/56816256/212166836-76ac8f12-137d-44cf-8513-36d92e5c7390.png)

**Comment by FreakPy** [comment]
Obrigado pela resposta galera
