### ISSUE TITLE
Meu perfil 👻

### ISSUE THREAD

**Issue by victorhugosr** [gustavoguanabara/git-github#2241]

**Comment by Sogayar** [comment]
Tudo bom meu nobre?? Me chamo **Henrique Sogayar**, sou novo na programação igual. Acredito que esteja vendo o Curso do Curso em vídeo de Git/GitHUB, mas o próprio Guanabara criou uma Issue própria pra divulgação do seu perfil [Clique aqui para começar seu comentário lá.](https://github.com/gustavoguanabara/git-github/issues/3)
