### ISSUE TITLE
Aprendendo a linguagem Markdown 🏖️

### ISSUE THREAD

**Issue by Diego0668** [gustavoguanabara/git-github#2269]
Testanto

**Comment by Diego0668** [comment]
# Programação
---
## Curso de Git e Github
Estou ~~aprendendo~~  _Markdown_ no curso de **Git e Github**
---

Lista Numerada:

1. Html
1. CSS
2. Java 
   1. JavaScript


Lista demarcada:

* Teste 
*  Teste1 
* Teste2


Lista de Tarefa:

- [x] Assistir o curso de Git e Github inteiro
- [x] Começar o curso de javascript
- [ ] Começar a tirar 900 em redações do Enem



![neymar](https://user-images.githubusercontent.com/107155067/221226186-90f69ab5-d2ea-40f1-a6eb-2b5ffaaaa1a0.png)


## Links

[Acesse o meu GitHub](https://github.com/Diego0668)

## Tabelas

Num | Nome | Nota 
---|---|---
1 | Diego | 10,0
2 | Geovanna | 8,0

Eu não entendo oq significa o comendo `document.getElementById()`  <-- CRASE 


## Olha meu programa em Python
` ` `
num = int(input('Digite um numero: ')
` ` `

## Escrevendo usando emoji 🥇 💯 ✌️

**Comment by TatianeAlencar** [comment]
**Testando a Linguagem**

-[ ] Ler

**Comment by TatianeAlencar** [comment]
##Testando a Linguagem Markdown

-[ ] Estudar
-[ ] Praticar

*Testar
*Testar
*Testar

![feliz](https://user-images.githubusercontent.com/112350691/221244187-e7d20511-27b8-4e3c-ae86-a6513a4aa398.jpg)

**Comment by TatianeAlencar** [comment]
## Testando a Linguagem **Markdown**
---

- [ ] Estudar 📖 
- [x] Praticar 🧑‍🎓 

* Testar
* estar
* Testar

### Tabela
Numero| Nome| Idade|
---|---|---
1 | Tati | 33
2 |Paulo | 22
3 | Joana| 25

![feli](https://user-images.githubusercontent.com/112350691/221246806-f8284519-a155-48bc-b127-0c1c7ff4caa6.jpg)

**Comment by TatianeAlencar** [comment]
## Testando a Linguagem **Markdown**
---

- [ ] Estudar 📖 
- [x] Praticar 🧑‍🎓 

* Testar
* estar
* Testar

### Tabela
Numero| Nome| Idade|
---|---|---
1 | Tati | 33
2 |Paulo | 22
3 | Joana| 25

![feli](https://user-images.githubusercontent.com/112350691/221246806-f8284519-a155-48bc-b127-0c1c7ff4caa6.jpg)
