### ISSUE TITLE
Professor e o mundo 4 de Python??????

### ISSUE THREAD

**Issue by PedroHenriqueSimoes** [gustavoguanabara/git-github#23]
Cadê o mundo 4 de Python fessor, estou esperando a um tempão :D

**Desculpe o incomodo, continue com suas aulas**

**Comment by LeonardoARGR** [comment]
Pô Orial

**Comment by PedroHenriqueSimoes** [comment]
@LeonardoARGR Foi uma **"piadinha",** sei que o professor esta se esforçando o máximo para conseguir fazer o Curso que esta sendo prejudicado graças a esta terrível `quarentena`  

Apesar de tudo, achei a aula do professor otima e estou ansioso para seguir este e outros cursos do Professor Guanabará, fique com um Octocat para você :D

![octocat](https://user-images.githubusercontent.com/62796106/78842223-d2cf0900-79d5-11ea-8178-b88498ac76db.png)

**Comment by marcelacdarocha** [comment]
Gafanhoto mestre, alguma previsão do mundo 4 de Python?

**Comment by rafaelbuttner** [comment]
Meu sonho esse mundo 4

**Comment by GabiBonza** [comment]
Bahhh seria muito bom hein... Ninguém ensina tão bem quanto o prof. Guanabara!

**Comment by FelipeDaguerre** [comment]
Também estou no aguardo do mundo 4, aprendi pra caramba nesses 3 primeiros mundos

**Comment by GuilhermeDev33** [comment]
Professor, pelo amor de Deussssssssssss, cadê o mundo 04????

Obs: Aprendi demais com os três mundo de python!

**Comment by GabiBonza** [comment]
Acho que deu alguma m**** muito grande... Pois passaram-se anos, e nada...

**Comment by luscianaderose** [comment]
mundo 4 plizzzz

**Comment by DevKauanBr** [comment]
**Cadê o mundo 4 ?**
 Aula 22 mundo 3 nos minutos 01:36 ele afirmou que iria ter o mundo 4. 😥

**Comment by JonasFirmiano** [comment]
F... mundo 4 not found : (

**Comment by fernandozilla** [comment]
Sonho com o mundo 4 diariamente... :(

**Comment by caiovfelipe** [comment]
Vocês tem ideia do que poderá ser tratado no mundo 4 de python? Do que será ensinado? 
Boa parte do conteúdo de python já foi abordados nos outros mundos.
Tem ideia do que será abordado? Do que não foi abordado nos mundos anteriores?

**Comment by GabiBonza** [comment]
> Vocês tem ideia do que poderá ser tratado no mundo 4 de python? Do que será ensinado? Boa parte do conteúdo de python já foi abordados nos outros mundos. Tem ideia do que será abordado? Do que não foi abordado nos mundos anteriores?

Toda a parte de orientação a objetos... Criação de classes, propriedades, herança, encapsulamento, classes nativas, etc.

**Comment by caiovfelipe** [comment]
> > Vocês tem ideia do que poderá ser tratado no mundo 4 de python? Do que será ensinado? Boa parte do conteúdo de python já foi abordados nos outros mundos. Tem ideia do que será abordado? Do que não foi abordado nos mundos anteriores?
> 
> Toda a parte de orientação a objetos... Criação de classes, propriedades, herança, encapsulamento, classes nativas, etc.

Hmm, vdd. Enquanto o mundo 4 não sai, sabe de algum outro lugar para aprender sobre esses tópicos?

**Comment by GabiBonza** [comment]
> > > Vocês tem ideia do que poderá ser tratado no mundo 4 de python? Do que será ensinado? Boa parte do conteúdo de python já foi abordados nos outros mundos. Tem ideia do que será abordado? Do que não foi abordado nos mundos anteriores?
> > 
> > 
> > Toda a parte de orientação a objetos... Criação de classes, propriedades, herança, encapsulamento, classes nativas, etc.
> 
> Hmm, vdd. Enquanto o mundo 4 não sai, sabe de algum outro lugar para aprender sobre esses tópicos?

Eu tenho aprendido muito no site https://realpython.com ... Eles possuem alguns conteúdos pagos, mas 80% dos artigos/tutoriais são gratuitos.

**Comment by ArthurSpeziali** [comment]
Sera que vai lançar o mundo 4 de python neste ano???

**Comment by EvandroBaraka** [comment]
Será que esse ano sai o mundo 4??

**Comment by caiovfelipe** [comment]
> Será que esse ano sai o mundo 4??

Acredito que sim. Um amigo meu, que conheceu o Guanabara presencialmente, falou que muito provavelmente sai na metade desse segundo semestre. Mas não consigo garantir nada.

**Comment by AyrtonCav** [comment]
Alguma previsão de lançamento do mundo 04??
