### ISSUE TITLE
Onde estão os slides da aula 4 ?

### ISSUE THREAD

**Issue by Gus303** [gustavoguanabara/git-github#2304]
Olá boa noite, eu gostaria de saber ondem estariam os slides da aula 4 pois não consegui a resposta

**Comment by Henriqueraa** [comment]
está no youtube, acessa o link [clicando aq para acessar a playlist com os videos](https://www.youtube.com/watch?v=mUZOySyVcuQ&list=PLHz_AreHm4dm7ZULPAmadvNhH6vk9oNZA&index=9)
