### ISSUE TITLE
Erro ao criar novo repositório 

### ISSUE THREAD

**Issue by CalebeArlan** [gustavoguanabara/git-github#233]
Estou com um problema chato, ao tentar criar um repositório ele aparece uma mensagem de erro, se alguém por favor puder me ajudar eu ficaria muito grato
![Capturar](https://user-images.githubusercontent.com/53148711/83314607-a07da300-a1f1-11ea-9790-ff052863dee5.JPG)

**Comment by Print-TesteServer** [comment]
@CalebeBR74 
## Você está criando um repositório em uma pasta de um repositório já existente.
 basta mudar a pasta que deseja salvar o repositório.

**Comment by CalebeArlan** [comment]
Mas eu não posso criar uma pasta para guardar todas as outras pastas de repositorio?

**Comment by Print-TesteServer** [comment]
pode, mas a pasta especifica que você quer salvar tem um repositório, literalmente.

 vou mandar uns prints, 1 min.

**Comment by CalebeArlan** [comment]
Enquanto você carrega suas prints, te mostro como esta a pasta:
![Capturar](https://user-images.githubusercontent.com/53148711/83797969-d6031000-a679-11ea-8c7d-ec83234761fe.JPG)

No caso Olá-Mundo é um repositório o mesmo desenvolvido durante o curso de Git e GitHub, e a pasta é onde eu quero salvo todos os repositórios, mas o problema surge quando eu não consigo colocar um novo repositório ali.

**Comment by Print-TesteServer** [comment]
# Se liga!
## Suponhamos que queira Usar a pasta = Jogo1 para colocar *TODOS* os seus repositórios
![Print 1](https://user-images.githubusercontent.com/64716025/83798023-f4690b80-a679-11ea-99fe-27fcfc593de0.PNG)
## A ultima pasta de destino para se criar o repositório deve ser a mesma.
![Print 2](https://user-images.githubusercontent.com/64716025/83798092-1498ca80-a67a-11ea-8d55-15c15cd91668.PNG)
## Dentro da pasta *Jogo1* tem um *REPOSITÓRIO*
![Print 4](https://user-images.githubusercontent.com/64716025/83798205-4b6ee080-a67a-11ea-9a0c-34728ac090ae.PNG)
![Print 5](https://user-images.githubusercontent.com/64716025/83798229-54f84880-a67a-11ea-9073-afb712b546c4.PNG)
# você não pode criar um repositório dentro de outro (Até onde sei)
![Print 3](https://user-images.githubusercontent.com/64716025/83798338-7ce7ac00-a67a-11ea-9db8-e4eafb8b10df.PNG)
### Como você quer deixar todos os repositorios em uma unica pasta você deve criar uma pasta para o mesmo.

Entendeu amigo?

.

**Comment by CalebeArlan** [comment]
Então eu tenho que criar uma pasta para o repositorio para assim depois assimilar essa pasta á uma pasta que contenha todos os repositorios?

**Comment by Print-TesteServer** [comment]
Só precisa de uma pasta(que não seja um repositório) para criar repositórios.

**Comment by CalebeArlan** [comment]
Sim, isso faz sentido, mas no meu caso mesmo que nem tenha um repositorio ele da esse erro olha só:
![Capturar](https://user-images.githubusercontent.com/53148711/83799227-df8d7780-a67b-11ea-8a75-7a127d1f7799.JPG)

Eu to tentando colocar nessa pasta, mas ele da o mesmo erro

**Comment by CalebeArlan** [comment]
E olha o erro: 
![Capturar](https://user-images.githubusercontent.com/53148711/83799304-faf88280-a67b-11ea-92c0-8455974d2803.JPG)

**Comment by CalebeArlan** [comment]
Isso era pra estar acontecendo?

**Comment by Print-TesteServer** [comment]
Ue...

**Comment by Print-TesteServer** [comment]
perae...
Cria uma pasta no propio GitHub desktop e vê se vai. apaga o TUDO, e escreve outra coisa.

**Comment by CalebeArlan** [comment]
Ok, vou fazer

**Comment by CalebeArlan** [comment]
Ok, eu coloquei direto no caminho, dai ele foi e o repositorio ta la dentro, agora sera que eu consigo por um outro repositorio nessa pasta?

**Comment by Print-TesteServer** [comment]
teste, é para funcionar.

**Comment by CalebeArlan** [comment]
Agora tentando colocar outro repositorio, ele não vai, da aquele mesmo erro

**Comment by Print-TesteServer** [comment]
o ultimo caminho, pasta é na que vc acabou de criar? ou no repositório que criou?

**Comment by CalebeArlan** [comment]
Na pasta vou mandar print

**Comment by CalebeArlan** [comment]
Olha esse é o mesmo caminho que eu usei no primeiro repositorio
![Capturar](https://user-images.githubusercontent.com/53148711/83799995-0ef0b400-a67d-11ea-8e7b-80550467c511.JPG)

**Comment by CalebeArlan** [comment]
Testa na sua maquina para ver se da o mesmo erro

**Comment by Print-TesteServer** [comment]
cria um repositório em: \Documents\Meus-Projetos\Outro-Repositório
esse ultimo repositório já criado coloca ele na pasta: Meus-Projetos.

**Comment by CalebeArlan** [comment]
Ok... um minuto

**Comment by Print-TesteServer** [comment]
você estava errando no seguinte, precisa colocar a pasta que quer salvar o repositório e depois a pasta do próprio repositorio. 

EX:
/Documents/Meus-projetos
Documents e Meus-projetos é o caminho.

me desculpe se não tinha explicado direito.. rsrs

**Comment by CalebeArlan** [comment]
Ok, fiz isso, fiz um repositorio "Outro-Repositorio", e no caminho deste repositorio ficou na pasta de mesmo nome conforme você comentou

**Comment by CalebeArlan** [comment]
Então pra cada repositorio eu tenho que criar uma pasta de mesmo nome?

**Comment by Print-TesteServer** [comment]
para cada repositório deve colocar o mesmo caminho e não criar uma pasta diferente.

**Comment by CalebeArlan** [comment]
Hum, entendi, certo, vou fazer assim daqui em diante.

Obrigado pela ajuda :smile:

**Comment by Print-TesteServer** [comment]
foi?
[veja o vídeo: 7:10](https://www.youtube.com/watch?v=5BYm7UdCrX0&list=PLHz_AreHm4dm7ZULPAmadvNhH6vk9oNZA&index=5)

**Comment by anafam82** [comment]
Estou com o mesmo problema. Ja tentei de tudo, ja criei nova pasta, ja tentei na pasta que ja estava colocando os outros arquivos da aula, mas não adianta. Não consigo habilitar o botão para criar novo repositorio.
![image](https://user-images.githubusercontent.com/67069920/105346402-4c7e5f00-5bc4-11eb-922f-d38ec157afe4.png)

**Comment by Print-TesteServer** [comment]
> @CalebeBR74
> 
> ## Você está criando um repositório em uma pasta de um repositório já existente.
> basta mudar a pasta que deseja salvar o repositório.
[veja o vídeo: 7:10](https://www.youtube.com/watch?v=5BYm7UdCrX0&list=PLHz_AreHm4dm7ZULPAmadvNhH6vk9oNZA&index=5)
