### ISSUE TITLE
O que é esse tal do slide 4???? ;-;

### ISSUE THREAD

**Issue by EDSDIOGO** [gustavoguanabara/git-github#2347]
nunca vou virar programador :(

**Comment by RodrigoRamone7** [comment]
Vai sim, pae. Esse é so o começo <3

**Comment by Berrsilva** [comment]
A aula 4 não tem slides, foi uma aula prática, por isso não existe os slides... isso foi só um exercício da aula 4! mas não desista amigo, também estou começando agora!
