### ISSUE TITLE
Onde está os slides da Aula 04?

### ISSUE THREAD

**Issue by RodrigoRamone7** [gustavoguanabara/git-github#2349]
Procurei os slides no repositório e não encontrei. Alguém consegue me enviar?

**Comment by brunotavaress** [comment]
#Test. A aula 04 não possui slides pois foi uma aula prática. Você pode assistir a aula disponível em [https://www.youtube.com/playlist?list=PLHz_AreHm4dm7ZULPAmadvNhH6vk9oNZA](url).

**Comment by RodrigoRamone7** [comment]
Muito obrigado pela sua colaboração!

Conheça meus projetos no perfil do [Github](https://github.com/RodrigoRamone7)
