### ISSUE TITLE
Teste a linguagem Markdown 

### ISSUE THREAD

**Issue by ghost** [gustavoguanabara/git-github#2415]
Utilize esse espaço para testar a linguagem Markdown.

**Comment by ghost** [comment]
_Estou aprendendo linguagem_ **Markdown** no ~~Curso em Vídeo de Git e GitHub~~

**Comment by ghost** [comment]
# Raffael

## Raffael

### Raffael

**Comment by ghost** [comment]
# Título 
___

**Comment by ghost** [comment]
# Aprendendo a Linguagem Markdown
---

## __*Podemos misturar as configurações*__
---

### Lista numerada:

1. Testando números 
1. Testando números 
1. Testando números 
   1. Testando números 
---

### Lista demarcada

* Teste
* Teste
   * Teste
* Teste
---

### Lista de tarefas:

- [ ] Levar o cachorro para passear
- [ ] Levar o gato para passear
- [x] Levar o macaco para passear
- [x] Levar o ornitorrinco para passear 
   

<PARTE 01>

**Comment by ghost** [comment]
# _Testando links_
---

## [Acesse meu github](https://github.com/RaffaelDiniz)

![ADT](https://user-images.githubusercontent.com/121104272/234569852-b946b132-75e0-4c1f-90a4-1c458344dbe8.jpg)

**Comment by ghost** [comment]
Número | Nome | Nota 
---|---|---
1 | Raffael | 97
2 | Diniz | 98
3 | Ferraz | 99
4 | Dias | 100

**Comment by ghost** [comment]
Alguém sabe me dizer o valor de Z? 

Exercício: 
`Z = 100 + 1 x 2`

**Comment by ghost** [comment]
Olá! 💫 🦘

**Comment by ghost** [comment]
> Teste de resposta

**Comment by leonardo-schneider** [comment]
Estou aprendendo a linguaguem **Markdown** no Curso em Video no *Github*
# Curso em Video
## Curso em Video2
### Curso em Video 3
***
Lista numerada:
1. Primeiro item
2. Segundo item
3. Terceiro item
***
Lista com Pontinhos:
* Primeiro
* Segundo
* Terceiro
***
Lista de tarefas:
- [ ] Fazer Alieninvasion
- [ ] Terminar de ver o curso
- [x] Tomar meu café

**Comment by leonardo-schneider** [comment]
Num | Nome | Nota
---|---|---
1 | Leonardo | 10
2 | Caca | 9
3 | Joao | 4.5
4 | Fer | 9

⚽

**Comment by leticia-jcj** [comment]
# Titulo nível 1 - usei 1 (#) no inicio da palavra com espaço
## Titulo nível 2  - usei 2 (#) no inicio da palavra com espaço
### Titulo nível 3 - usei 3 (#) no inicio da palavra com espaço
***
A linha acima foi criada com 3 (***)
Estou ~~aprendendo~~ linguagem __Markdown__ no *Curso em Vídeo* de Git e GitHub
Podemos __*misturar as configurações*__

Lista enumerada:
1. Teste 1
1. Teste 2
   1. Teste 2.1
   2. Teste 2.2
1. Teste 3

Lista demarcada:
* Teste 1
   * Teste 1.2
* Teste 2
* Teste 3

Lista de tarefas:
- [ ] Finalizar o curso de Git e Github;
- [x] Verificar e-mail;
- [ ] Assistir à aula de PHP.

![robot-pixabay](https://user-images.githubusercontent.com/75034945/235275942-56df040d-b97b-4fc0-9004-8c373c865e74.jpg)

[Acesse meu Github](https://github.com/leticia-jcj)

**Comment by leticia-jcj** [comment]
## Tabela 1

Num | Nome | Nota
---|---|---
1 | Lena | 9.3
2 | Lucas | 9.0
3 | Maria | 5.3
4 | Aline |10.0

## Tabela 2

Código | Descartáveis | Valor
---|---|---|
2023 | Copo | R$ 2.60
5485 | Prato | R$ 5.22
2583 | Colher | R$ 4.66
5425 | Guardanapo | R$ 1.99

## Trecho de Programa
Meu *primeiro* código em `Java`.
```
import java.util.Scanner;

public class Media {
   public static void main(String[] args) {
      Scanner sc = new Scanner(System.in);

      System.out.print("Digite o primeiro número: ");
      double num1 = sc.nextDouble();

      System.out.print("Digite o segundo número: ");
      double num2 = sc.nextDouble();

      double media = (num1 + num2) / 2;

      System.out.println("A média entre " + num1 + " e " + num2 + " é " + media);
   }
}


```

:sweat_smile:

**Comment by Alicesousaa** [comment]
* teste
- teste
- teste

- [ ] abrir app
- [x] fechar app
_FUI A FEIRA_ *COMPRAR ROMÃ* **ESQUECI E COMPREI MORANGO**
