### ISSUE TITLE
Onde está os slides da Aula 04 professor?

### ISSUE THREAD

**Issue by davimgfx** [gustavoguanabara/git-github#2434]
Desde já, obrigado pelo excelente conteúdo.

**Comment by peixotots** [comment]
Olá!
Essa aula não tem slides, pois foi uma aula prática. Vc pode acessá-la [neste link](https://www.youtube.com/watch?v=gMh6lrXibWY&list=PLHz_AreHm4dm7ZULPAmadvNhH6vk9oNZA&index=4) 

_Resposta teste elaborada durante o curso de Git e GitHub._

![Sem título](https://github.com/gustavoguanabara/git-github/assets/121225521/d13bbe7c-cf19-41ec-aa03-217b4c339592)

**Comment by davimgfx** [comment]
Obrigado colega!
**Resposta teste elaborada durante o curso de Git e GitHub.**
