### ISSUE TITLE
Por que 42?

### ISSUE THREAD

**Issue by GabrielTMedeiros** [gustavoguanabara/git-github#25]
Eu sei que é a resposta para a vida, o universo e tudo mais; mas por quê raios é 42? E qual criptografia usa?

**Comment by gustavoguanabara** [comment]
Pergunte ao Google! Ele sabe 👀 HAHAHA

[Curiosidades](https://super.abril.com.br/blog/turma-do-fundao/feliz-dia-da-toalha-18-curiosidades-sobre-o-guia-do-mochileiro-das-galaxias/)
