### ISSUE TITLE
Estudando git-github em 07/2023 onde esta o slides da aula 04 .

### ISSUE THREAD

**Issue by LeonardoGomes2** [gustavoguanabara/git-github#2574]
aula pratica.

**Comment by kauagamap** [comment]
Também estou acompanhando o curso em 2023

**Comment by LeonardoGomes2** [comment]
muito bom, as aulas e o conteúdo são bem práticos de se aprender.

**Comment by EdipoGeoge** [comment]
## GitGitGit
Aprendendo **GitGitHub** com professor Guanabara

Lista numerada:
1. Geoge
1. Édipo
 
lista dermacada:

* vai corinthians

**Comment by RamilaMacedo** [comment]
Melhor professor! **Aula 4**- ***prática Git Hub!***
