### ISSUE TITLE
Não consigo criar ou subir nada pelo Vscode

### ISSUE THREAD

**Issue by LucasMascarenhasLima** [gustavoguanabara/git-github#2659]
Olá eu estou fazendo o curso de Git e Github ficou claro que isso facilita a vida demais, mas não consigo criar pasta, nem arquivo o que pode ser me ajudem aí por favor, eu consegui fazer um html mais foi inverso, digitei no VS e copie e colei no Github online 
![image](https://github.com/gustavoguanabara/git-github/assets/88747894/471f3502-ace3-452e-8d9d-596901fab44f)

**Comment by JonatasCamargo** [comment]
Olá Lucas!

Creio que não chegou a ver os vídeos do inicio do curso de Git e Github. No quinto vídeo da playlist explica bem detalhadamente sobre como fazer um repositório e até como salvar automático suas linhas de código, pois, ao meu ver não chegou a configurar está opção, porque ali na parte superior a "bolinha branca" indica que não está salvo.

Espero ter ajudado em algo, abs!

**Comment by LucasMascarenhasLima** [comment]
Fala @JonatasCamargo amigo eu assisti essa aula duas vezes quase, fiz as configurações, quando o VS tenta salva diz que não foi possível salva, tentei até dar uns CTRL + S mesmo assim não salva, aí estou procurando a solução aí, mas valeu pela ajuda.

**Comment by LucasMascarenhasLima** [comment]
@JonatasCamargo mano eu consegui resolver, uma das mudanças que eu fiz foi instalar como adm e seguir passo a passo tudo que o guanabara falou.
