### ISSUE TITLE
Onde estão os slides da aula 04? 😇

### ISSUE THREAD

**Issue by cristianofl** [gustavoguanabara/git-github#2676]
Procurei os slides da aula 04 e não encontrei. Alguém poderia procurar pra mim?

**Comment by cristianofl** [comment]
Finalizado!
**Issue** criada para acompanhamento da aula.

**Comment by ManoelaAugsta** [comment]
https://github.com/gustavoguanabara/git-github/issues/5#issuecomment-611226237

resposta

**Comment by Etelvino-programmer** [comment]
valeu @ManoelaAugsta
