### ISSUE TITLE
Como faço para colocar meu projeto Privado Publico Novamente 

### ISSUE THREAD

**Issue by JonasBezerra** [gustavoguanabara/git-github#269]
# Bom dia Gafanhoto Mestre!. 🖖
***
   Hoje fui criar um repositório e sem querer coloquei como **Privado**.
   Como irei fazer para colocar ele **Público Novamente.?**
   * Será que terei que apagar o repositório?
   * E como faço isso pelo gitHub Desktop.?

**Comment by Felipe-Santos97** [comment]
boa tarde @JonasBezerra , vc não precisa apagar o repositório para deixar ele publico.

Basta ir no seu repositório no Github, em seguida procurar por configurações (settings) e la vai ter uma área escrito **Danger zone** com a opção **Change repository visibility**. Ai é só mudar para publico.

Espero ter ajudado

**Comment by JonasBezerra** [comment]
## Muito obrigado!. _@Felipe-Santos97_
---
   ### Deu super Certo!. Grato pela Ajuda. Já ganhou um Seguidor! 👍
