### ISSUE TITLE
Em pleno fim de 2023 não tem o slide da aula 4

### ISSUE THREAD

**Issue by LucasCamara13** [gustavoguanabara/git-github#2721]

**Comment by LucasCamara13** [comment]
![boruto-uzumaki-1493397105426_v2_1x1](https://github.com/gustavoguanabara/git-github/assets/140122250/505bc543-db7d-47c5-aef1-6424977f8ac8)
[aqui](https://animesonlinecc.to/anime/black-clover/)

**Comment by JoaoDch** [comment]
amigao por favor ne...
