### ISSUE TITLE
Test 👍

### ISSUE THREAD

**Issue by ishugodev** [gustavoguanabara/git-github#2757]
Test issue

**Comment by ishugodev** [comment]
Se for no windows, consegue colocar emoji usando Win+. também

**Comment by ishugodev** [comment]
😎

**Comment by hugoish** [comment]
> 😎
 oi


> Se for no windows, consegue colocar emoji usando Win+. também

oi

**Comment by ishugodev** [comment]
> 😎

obrigado

**Comment by ishugodev** [comment]
> Se for no windows, consegue colocar emoji usando Win+. também

verdade
