### ISSUE TITLE
Onde estão os slides da aula 04?

### ISSUE THREAD

**Issue by deDeusThiago** [gustavoguanabara/git-github#2770]
Escrevo isso como forma de treinamento  para acompanhar a aula 09 do curso de Git do saudoso professor Guanabara. Obrigado, professor!

**Comment by abmaelmarques** [comment]
estou por aqui tambem hahaha

**Comment by falbertocs** [comment]
Estou assistindo a aula no dia 01/11/2023 pelo youtube. Obrigado Guanabara por disponibilizar esse conteudo de forma gratuita e totalmente didatica.
