### ISSUE TITLE
Onde está os slides da aula 4?

### ISSUE THREAD

**Issue by BrenoReisSilva** [gustavoguanabara/git-github#2842]
Procurei os slides da aula 04 e não encontrei. Alguém poderia atualizar para mim?

**Comment by Symonsy** [comment]
Foi uma aula prática, vai assistir as aulas zé ruela

**Comment by rafitsdev** [comment]
@Symonsy provavelmente ele ta só testando a aula de issues do curso de git-github <3

**Comment by deborajosue** [comment]
não achei
