### ISSUE TITLE
Erro ao tentar dar um Commit no Git pelo aplicativo GitHub Desktop

### ISSUE THREAD

**Issue by StellaMFB** [gustavoguanabara/git-github#2850]
Basicamente: quando fui tentar dar um commit após excluir alguns arquivos de um repositório apresentou-se o seguinte erro:
![Captura de tela de 2023-12-22 23-30-52](https://github.com/gustavoguanabara/git-github/assets/153751549/d15ebb46-fb97-4083-99b8-ad8c0ad97677)

Se alguém puder me ajudar, por favor. Desde já agradeço.

**Comment by devcristianhr** [comment]
Se tiver uma branch que contenha os arquivos, volte nessa versão dela, e a partir dai faças as atualizações necessárias.

**Comment by StellaMFB** [comment]
Obrigada
