### ISSUE TITLE
Meu nome é Renan Cardoso, sou do Rio de Janeiro, atualmente estudando e me especializando em Front-end.

### ISSUE THREAD

**Issue by RenanCardosoA** [gustavoguanabara/git-github#2870]
Por enquanto ainda não possuo bons projetos, ou tão complexos, porém, estou fazendo o curso de _JavaScript_ do @cursoemvideo, também estou desenvolvendo _mini projetos_ para praticar, são ideias que retirei do _YouTube_, logo abaixo estão meu repositórios:
* [ Curso de JavaSript ](https://github.com/NanProg/Curso-JavaScript)
* [Mini projetos](https://github.com/NanProg/Mini-Projetos)
Meu **perfil** onde divulgo minhas experiências **->** @NanProg

**Comment by aderitoapelao** [comment]
forca ai mano
