### ISSUE TITLE
Eu vendo o professor fechando essas Issue tudo dps

### ISSUE THREAD

**Issue by PedroHenriqueSimoes** [gustavoguanabara/git-github#29]
`GITHUB`
**Adorei essa aula, super divertido fazer issues em seu perfil**

adorei
![We_are](https://user-images.githubusercontent.com/62796106/78839490-f3479500-79ce-11ea-85d0-50d9718b9ab7.jpg)

**Comment by gustavoguanabara** [comment]
Também me diverti muito! AHAHHAA
