### ISSUE TITLE
Posso recuperar os projetos depois de formatar o PC?

### ISSUE THREAD

**Issue by leoelias12** [gustavoguanabara/git-github#2914]
Se eu formatar o meu PC sem salvar a pasta de projetos do GitHub, eu perco essa pasta, mas quando eu reinstalar o GitHub Desktop eu consigo puxar tudo de novo pro computador automaticamente, ou preciso baixar individualmente os que foram clonados e os meus repositórios próprios?

**Comment by rafinha-dev** [comment]
> Se eu formatar o meu PC sem salvar a pasta de projetos do GitHub, eu perco essa pasta, mas quando eu reinstalar o GitHub Desktop eu consigo puxar tudo de novo pro computador automaticamente, ou preciso baixar individualmente os que foram clonados e os meus repositórios próprios?

O Github desktop não baixa seus projetos automaticamente. Precisa selecionar o projeto e fazer o download (caso ele esteja no GitHub) ou outro local.

**Comment by GabrieldeSouzaBraz** [comment]
Se antes de formatar o seu computador, você colocar seus projetos no repositório remoto aqui no GitHub, basta vc instalar o Git e o GitHub Desktop no seu PC após a formatação, entrar com sua conta do GitHub no desktop, e clonar o seu próprio repositório remoto pro seu local. acho que era essa sua dúvida.

**Comment by rafinha-dev** [comment]
> 
De fato foi uma pergunta um pouco confusa. Mas acredito que sua resposta deve solucionar a dúvida.

**Comment by leoelias12** [comment]
Obrigado @rafinha-dev  e @GabrieldeSouzaBraz . Minha dúvida foi respondida
