### ISSUE TITLE
Onde estão os slides da Aula 04?

### ISSUE THREAD

**Issue by kaikem** [gustavoguanabara/git-github#3168]
*TESTE DA AULA 09*

Procurei os slides da aula 04 e não encontrei.
Alguém poderia atualizar para mim?

**Comment by kaikem** [comment]
Não existem slides para a aula 04!

**Comment by kaikem** [comment]
*TESTE DE ADIÇÃO DE IMAGEM*
![positivo](https://github.com/gustavoguanabara/git-github/assets/46039151/5d997b20-83c8-46e0-abab-b82e71f500f3)

**Comment by kaikem** [comment]
*TESTE DE LINK*
[Repositório de Kaike Marósica](https://github.com/kaikem)

**Comment by amandaCostaDeOliveira** [comment]
Aprendendooo!
