### ISSUE TITLE
Testando Markdown e inserir imagens ou docs

### ISSUE THREAD

**Issue by IsaqueR02** [gustavoguanabara/git-github#3191]
#Teste
### teste
**teste**
*teste*, _testando_
~~Um testes~~
**Teste** **_dois_**
***Teste três***
<sub>Teste 4</sub>
<sup> Teste Final </sup>
![Teste](https://github.com/gustavoguanabara/git-github/assets/71456433/13669703-d6f5-4b87-b1cd-967f2c5acc1d)

'RRGGBB' teste

**Comment by Amandaad** [comment]
<div align="center">
  <h3>Amanda SImplicio</h3>
  <p>Este parágrafo também fica centralizado</p>
</div>

**Comment by Amandaad** [comment]
<div style="border:1px solid #ccc; padding:10px; background:#f9f9f9">
  <strong>Nota:</strong> Este é um bloco destacado com borda e fundo.
</div>

**Comment by Amandaad** [comment]
#4514 

<div align="center">
  <img src="https://github.com/gustavoguanabara/git-github/assets/71456433/13669703-d6f5-4b87-b1cd-967f2c5acc1d" width="200"/>
  <p><em>Legenda em itálico</em></p>
</div>
