### ISSUE TITLE
TESTANDO A LINGUAGEM MAKDOWN!

### ISSUE THREAD

**Issue by CaValk4** [gustavoguanabara/git-github#3237]
teste:

estou _aprendendo_ a linguagem **markdown** no ~~curso em video~~ de Git e GitHub

# Aula de _**linguagem**_ markdown
***
## Lista numerada:

1. teste
2. teste2
3. teste3
   1. sub-teste
   1. sub-teste2

***

## Lista demarcada:

* teste
* teste2
* banana
   * banana da terra
   * banana prata
   * banana maçã
   * banana nanica
* teste3 

***

## Lista de tarefas:

- [ ] Concluir curso de git e gitHub do curso em video
- [x] assistir pelo menos 2 aulas p/ noite
- [x] escovar os dentes
- [x] procurar estágio

***

## Imagens e Links:

![O maior do Nordeste!](https://github.com/gustavoguanabara/git-github/assets/146299450/8ce7b26c-dac7-42c2-9fdd-3021944b3269)

![image](https://github.com/gustavoguanabara/git-github/assets/146299450/a16402c4-7041-4a93-ab9d-8b39c343c9f1)

clique para acessar a [amazon](https://www.amazon.com.br)!

***

## Tabelas

matricula | Nome | Nota
---|---|---
1 | Vitor | 0
2 | guanabara | 9,95
3 | Ariel | 10

***

## Trecho de códigos:

EX: não sei para que serve `import { Request, Response } from "express"` em um projeto back-end.

Conectando projeto a um banco de dados MySQL:
```
const connection = knex({ // Estabelece conexão com o banco
    client: "mysql",
    connection:{
      host: process.env.DB_HOST,
      port: 3306,
      user: process.env.DB_USER,
      password: process.env.DB_PASSWORD,
      database: process.env.DB_SCHEMA,
      multipleStatements: true
    }
})

export default connection;
```
***

## emojis

olá pessoal 😸 🗾 🔢 🖌️ 🐒 

***
# esse foi meu aprendizado de linguagem __*Markdown*__

Adeus!

![image](https://github.com/gustavoguanabara/git-github/assets/146299450/24466f95-defb-4b8e-9c4a-63def665669a)

**Comment by carvalhomaykon** [comment]
# Linguagem Makdown
Estou aprendendo a linguagem ~~__Markdown__~~ no Curso em Video de **Git e Github**

__Lista Enumerada__:
1. Teste
2. Teste2
   2.1. Teste2.1
3. Teste3

**Lista Demarcada:**
* Teste
* Teste
   * Teste
- Teste

__Lista de Tarefas:__
- [ ] Criar a página principal
- [ ] Finalizar Reunião
- [ ] Aguardar Pagamento

## Adicionar Imagens
![github-mark](https://github.com/gustavoguanabara/git-github/assets/139561498/77c09ac8-7d39-4e5d-bcab-6d1d9f150f6f)

## Criar Links
** Lista Minhas Redes Sociais: **
* [GitHub](https://github.com/)
* [Linkedin](https://www.linkedin.com/public-profile/settings?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_self_edit_contact-info%3BsrmBAck7RhWRgoP6nA%2FfRQ%3D%3D)

## Tabela
Num | Nome | Nota
---|---|---
1 | Maykon | 10
2 | Gustavo | 8,5
3 | Maria | 9,5

Terminou a tabela

## Dúvida
Não entendo direito para que serve  o comando `document.getElementById()` da linguagem JavaScript

## Colocar Código do Programa
```
num = int(input('Digite um valor: '))
if num % 2 == 0:
   print (f'O valor {num} é PAR')
else:
  print (f'O valor {num} é IMPAR')
```

## Colocar Emojis
Olá alunos do Gafanhoto 🖖 🐤  👍 💯 💣 🐒 

> Será que vai chover hoje?

**Comment by 0bio0** [comment]
# aula de makdown 
lista numarada:

1. teste
2. teste
3. teste
4. teste

lista demarcada:
* teste
* teste
* teste
* teste

lista da tarefas:
- [x] teste
- [x] teste
- [ ] teste
- [ ] teste

**Comment by codeByArthur** [comment]
# Título (h1)
## Título (h2)
### Título (h3)
---
***
linhas acima

Estou aprendendo linguagem **Markdown** no Curso em Vídeo de Git e GitHub (**Negrito**  **)
Estou aprendendo linguagem __Markdown__ no Curso em Vídeo de Git e GitHub (__Negrito__ __)

Estou aprendendo linguagem *Markdown* no Curso em Vídeo de Git e GitHub (*Itálico*  *)
Estou aprendendo linguagem _Markdown_ no Curso em Vídeo de Git e GitHub (_Itálico_  _)

Estou aprendendo linguagem ~~Markdown~~ no Curso em Vídeo de Git e GitHub (~~Riscado~~ ~~)

Podemos __*misturar configurações*__ (__*Negrito e Itálico*__  __*)


Lista númerada (deve-se usar um número qualquer em seguida do ponto e espaço):

1. Teste 1
   1. Teste 2
1. Teste 3

Lista demarcada (deve-se usar * ou -, em seguida de um espaço):

* Teste
* Teste 
* Teste
   * Teste
* Teste

Lista de tarefas (deve-se usar - [ ], em seguida de um espaço) (colocando um x dentro do colchete a tarefa fica como feita):

- [ ] Criar página do cliente
- [x] Criar página do cliente
- [x] Criar página do cliente 
- [ ] Criar página do cliente


Colocar imagem:

![descrição da imagem](link da imagem)
![Imagem do Santástico](https://github.com/gustavoguanabara/git-github/assets/168872194/ac0624e5-80c8-4660-b252-b28b5fb26df7)


Colocar link: 

[Texto do link](link)
[Meu instagram](https://www.instagram.com/arthuraraujod_silva/)


Criando tabelas:

Num | Nome | Nota
---|---|---
1 | Arthur | 9,0
2 | José | 10,0
3 | Enzo | 9,5



CÓDIGOS:

Não entendo direito para que serve o comando `document.getElementById()` da linguagem JavaScript

Olha meu comando em python

```
num = int(input('Digite um valor:  ')
if num % 2 == 0:
    print(f'O valor {num} é PAR')
else
    print(f'O valor {num} é IMPAR')
```

EMOJIS (só dar : que ele ja da as sugestões):

Ola pequeno gafanhoto 😄

**Comment by CaValk4** [comment]
![image](https://github.com/gustavoguanabara/git-github/assets/146299450/6eb6e752-aa56-405a-abc7-724778fa873c)
