### ISSUE TITLE
divulgação de perfil esta bloqueada 

### ISSUE THREAD

**Issue by Lucassantos1990** [gustavoguanabara/git-github#3293]
estou na aula de **issues** e não consegui divulgar meu perfil.

**Comment by th1rt3en13** [comment]
Olá Lucas, isso ocorreu pois chegou ao limite máximo de comentários. Observei alguns alunos criando novas como na #162 e #2837 . 
Abraços!

**Comment by Lucassantos1990** [comment]
obrigado @th1rt3en13
