### ISSUE TITLE
Onde estão os slides da Aula 04?

### ISSUE THREAD

**Issue by marlongordon** [gustavoguanabara/git-github#3324]
Procurei os slides da aula 04 e não encontrei. Alguém poderia atualizar pra mim?

Obs.: Issue teste, obviamente.

**Comment by VictorPresenca** [comment]
tmb quero saber.

Obs.: teste

**Comment by marlongordon** [comment]
"Lambda, lambda, lambda, nérdês!!!" - Nerd, Jovem.

![image](https://github.com/user-attachments/assets/8e2c3140-95a3-404f-9e7c-1882a015a5c7)

Teste de link de imagem

**Comment by marlongordon** [comment]
Como teste de link de site eu vou redirecionar para o meu [GMBinder](https://www.gmbinder.com/profile/JackTatoo).

GMBinder é um site para divulgar homebrews de Dungeons & Dragons e cada documento é programado dentro do site e se baseando em CSS.
