### ISSUE TITLE
Testando Markdown

### ISSUE THREAD

**Issue by alekswheeler** [gustavoguanabara/git-github#354]
![168-1682213_the-wheres-waldocat-github-octocat](https://user-images.githubusercontent.com/57152476/90693958-21c35f80-e24e-11ea-92fe-5d83a3d2b000.png)

**Comment by engMarcusArthur** [comment]
#353 __teste__

**Comment by codeIsrael-zz** [comment]
### Bom dia!
Todos os meus teste eu fiz direto no Visual Code. **Fica a Dica!**

![Captura de tela de 2020-08-21 08-48-31](https://user-images.githubusercontent.com/62953554/90887638-1e81be00-e38b-11ea-80c2-3128499799e7.png)
![Captura de tela de 2020-08-21 08-49-18](https://user-images.githubusercontent.com/62953554/90887700-3b1df600-e38b-11ea-999e-d187f9c0f033.png)
![Captura de tela de 2020-08-21 08-49-55](https://user-images.githubusercontent.com/62953554/90887754-4e30c600-e38b-11ea-8da9-81416d0400a4.png)

**Comment by Dev3lopmentM4chine** [comment]
![daftpunktocat-guy](https://user-images.githubusercontent.com/68969699/90917913-273db880-e3ba-11ea-9094-baed28c3708c.gif)

**Comment by alekswheeler** [comment]
@codeIsrael  Muito Obrigado pela dica!
