### ISSUE TITLE
Aplicativo IMC

### ISSUE THREAD

**Issue by DavidAluno184** [gustavoguanabara/git-github#38]
Meu GitHub: **@DavidAluno184**
Aplicativo de calcular IMC: https://github.com/DavidAluno184/CursoANDROID/tree/master/Projeto%20Final/Aplicativo

**Comment by arthurprioli** [comment]
Cara, achei interessante seu projeto, um conselho, ao invés de colocar em zip. Coloca os arquivos do projeto no seu GitHub, sem precisar do zip.
