### ISSUE TITLE
É possível  clonar somente uma pasta  de um repositório ao invés do repositório inteiro?

### ISSUE THREAD

**Issue by Victordop** [gustavoguanabara/git-github#383]
![Captura de tela de 2020-09-03 18-14-44](https://user-images.githubusercontent.com/70064706/92176369-b0baa500-ee14-11ea-9eac-8419111932b1.png)

Por exemplo, clonar somente a pasta imagens do repositório acima.

Obrigado por sua colaboração! :wink:

**Comment by Pedro1470** [comment]
baixa ela

**Comment by Victordop** [comment]
Onde fica essa opção, @Pedro1470 ?

**Comment by Pedro1470** [comment]
acho que você vai ter que baixar todas e depois copiar ela.
lá em "code" e "Download zip"

**Comment by Pedro1470** [comment]
Ou voce pode clicar em cada imagem e ir salvando uma por uma

**Comment by Victordop** [comment]
Deu certo! Muito obrigado pela ajuda :)
