### ISSUE TITLE
Erro repositório

### ISSUE THREAD

**Issue by MatheusRodri** [gustavoguanabara/git-github#384]
;Ao criar um novo repositorio aparece o seguinte erro:  "This directory appears to be a GIT repository. Would you like to add this repository instead?" alguém pode me ajudar 
![image](https://user-images.githubusercontent.com/24962913/92181461-a94cc900-ee1f-11ea-9fb1-1ef2c3b07315.png)

**Comment by luumarodrigues** [comment]
Aconteceu comigo uma vez e talvez possa te ajudar. 
O que aconteceu comigo foi que na pasta que eu estava tentando criar o repositório já tinha um arquivo oculto .git criado.

Para resolver isso vc precisa ir até a pasta **MeusProjetos** e exibir os arquivos ocultos (se estiver no MAC, é só dar `Command (⌘) + Shift + .`) e o arquivo **.git** vai aparecer, se isso acontecer, é só você deletar ele e tenta criar o repositório novamente. Caso não tenha nenhum arquivo .git nessa pasta, verifique na pasta do seu usuário, pois ele pode estar lá também.

**Comment by MatheusRodri** [comment]
Muito Obrigado !!!!!!

**Comment by anafam82** [comment]
Também tive o mesmo problema. Obrigada!!! Deletei e deu certo. Mas será que teremos que fazer isso sempre?
