### ISSUE TITLE
Teste (curso git github)

### ISSUE THREAD

**Issue by romaopatrick** [gustavoguanabara/git-github#394]
Procurei os slides da aula 04 e não encontrei, alguém poderia atualizar pra mim?

**Comment by victorangelov** [comment]
Caro, @romaopatrick a aula 4 foi prática e não possui slide, você pode acessar clicando [aqui](https://www.youtube.com/watch?v=gMh6lrXibWY&list=PLHz_AreHm4dm7ZULPAmadvNhH6vk9oNZA&index=4)
![supino inclinado](https://user-images.githubusercontent.com/53021597/92545182-f963cb00-f225-11ea-8fc7-31ecf2b110b9.JPG)
