### ISSUE TITLE
Buenas!!!!!

### ISSUE THREAD

**Issue by Evandromotta** [gustavoguanabara/git-github#411]
## Olá Pessoal,
 Divulgando meu repositório.

* Meu repositório no [GitHub](https://github.com/Evandromotta)

**Me encontre nas redes sociais:**
* [Likedin](www.linkedin.com/in/evandrosmotta)
* [Instagram](https://www.instagram.com/evandrosmotta/)

**Comment by RuhtraX** [comment]
Chefe, isso não deveria estar na issue #3 não?
