### ISSUE TITLE
Livros sobre programação em PT-BR

### ISSUE THREAD

**Issue by zekicarvalho** [gustavoguanabara/git-github#42]
Repositório com dezenas de livros sobre programação.
[free-programming-books](https://github.com/zekicarvalho/free-programming-books/blob/master/free-programming-books-pt_BR.md)

**Comment by but-1-eno** [comment]
O livro que o professor Gustavo Guanabara citou em aula é o Conhecendo o GIT. [Confere lá na Amazon.](https://www.amazon.com.br/Conhecendo-Git-EUSTAQUIO-RANGEL-OLIVEIRA-ebook/dp/B008B07KWM)

**Comment by zekicarvalho** [comment]
> O livro que o professor Gustavo Guanabara citou em aula é o Conhecendo o GIT. [Confere lá na Amazon.](https://www.amazon.com.br/Conhecendo-Git-EUSTAQUIO-RANGEL-OLIVEIRA-ebook/dp/B008B07KWM)

@but-1-eno Bacana, mais um pra lista.

**Comment by gustavoguanabara** [comment]
Ótimas dicas! Lá eles só disponibilizam livros free? Não rola pirataria? 🖖

**Comment by zekicarvalho** [comment]
> Ótimas dicas! Lá eles só disponibilizam livros free? Não rola pirataria? 🖖

Vlw, são só livros gratuitos usado em instituições de ensino (algumas federais).

**Comment by gustavoguanabara** [comment]
Maravilha! Já deixei sua Issue marcada aqui! Obrigado pela colaboração!
