### ISSUE TITLE
Onde está a aula 04? (TESTE)

### ISSUE THREAD

**Issue by henriquefb1** [gustavoguanabara/git-github#423]
Procurei os slides da aula 04 e não encontrei.

Alguém poderia me atualizar?

====TESTE====

**Comment by camargo800** [comment]
![Meliodas](https://user-images.githubusercontent.com/70231656/94312652-a5f6ba00-ff53-11ea-9647-a70b83e81e4a.png)
 Não tem.
[Acesse meu perfil](https://github.com/camargo800)

**Comment by camargo800** [comment]
Olá @gustavoguanabara 🖖🏻

**Comment by vladimirmaciel** [comment]
@gustavoguanabara , também quero saber
