### ISSUE TITLE
É possível reabrir uma issue?

### ISSUE THREAD

**Issue by drawsoft** [gustavoguanabara/git-github#44]
@gustavoguanabara estou acompanhando o seu curso e sua didática é fenomenal. Parabéns! 

Mas segue a dúvida que me surgiu durante a aula de issues.
É possível reabrir uma issue que colocamos com concluída?

Obrigado

**Comment by gustavoguanabara** [comment]
É possível sim. @drawsoft ! Se o papo continuar e você sentir necessidade, pode clicar em Reopen Issue que fica lá embaixo da página, ao lado do botão de postar um novo comentário 🖖
