### ISSUE TITLE
Tem como saber quais/quantas pessoas clonaram meu repositórios?

### ISSUE THREAD

**Issue by rafaeljsc** [gustavoguanabara/git-github#447]
Seria interessante ter esse controle, assim daria pra saber se as pessoas estão se interessando nos meus projetos

**Comment by MariliaCuri** [comment]
Olá @rafaeljsc Oi Rafael, tudo bem?

Eu achei a seguinte informação no Stackoverflow:

"Para saber quantas vezes o código fonte do seu repositório foi clonado em um determinado dia, bem como quantos usuários do GitHub (ou endereços IP anônimos) fizeram a clonagem, vai na aba Traffic, ela mostra um monte de informações sobre quem está visitando seu repositório na web."

Espero ter ajudado ;)

**Comment by rafaeljsc** [comment]
@MariliaCuri  perfeito, brigadão pela força!
