### ISSUE TITLE
Teste da aula Markdown

### ISSUE THREAD

**Issue by GuiBarreto** [gustavoguanabara/git-github#481]
# Teste Título Nível 1
---
## Teste Título Nível 2
***
### Teste Título Nível 3
---

Teste  **Curso em vídeo** em negrito
Teste  *Curso em vídeo* em itálico
Teste  ~~Curso em vídeo~~ riscado
Teste  __*Curso em vídeo*__ *misturando* **configurações**

Lista numerada

1. teste 1
2. teste 2
   2. sub-teste 2
3. teste3

Lista demarcada

* Teste
* Teste
   * Teste
* Teste

Lista de Tarefas
- [x] Tarefa 1
- [x] Tarefa 2
- [ ] Tarefa 3
- [ ] Tarefa 4

![123](https://user-images.githubusercontent.com/59628617/96608062-59429c80-12cf-11eb-95c4-d0f0255d1b6f.png)

[Acesse meu GitHub](https://github.com/GuiBarreto)

Num | Nome | Nota
---|---|---
1 | Guilherme | 10
2 | Thaís | 9.5
3 | Bruno | 9.2
4 | Ozzy | 9.7
terminou a tabela

Não entendo direito para que serve o comando `document.getElementById()` da linguagem JavaScript

Olhe meu programa em Python
```
a = int(input('Digite o primeiro valor: '))
b = int(input('Digite o segundo valor: '))
c = int(input('Digite o terceiro valor: '))
menor = a
if b<a and b<c:
    menor = b
if c<a and c<b:
    menor = c
maior = a
if b>a and b>c:
    maior = b
if c>a and c>b:
    maior = c
print('O menor valor é {} e o maior é {}'.format(menor, maior))
```
Olá, pequenho Gafanhoto 🖖

**Comment by aliners28** [comment]
Num| Nome| Nota
---|---|---|
1| Aline| 9 |
2| José| 10|
3| Paula| 8|
terminou tabela


olá :vulcan_salute:

**Comment by GuiBarreto** [comment]
@aliners28 vlw eu tinha esquecido desse detalhe rsrs

**Comment by abraaovilanova** [comment]
#Título 1
***
##  Titulo 2
---
### Titulo 3
Estou aprendendo a linguagem **Markdown**
Negrito e itálico _*Testando*_

1. Teste
2. Test 2
* Teste

Lista de Tarefas

- [x] Criar a página principal
- [ ] Receber pagamentos

[Acesse meu GitHub](http://github.com/abraaovilanova)
