### ISSUE TITLE
Onde está os slides da aula 04 (teste)

### ISSUE THREAD

**Issue by GuilhermeLima182** [gustavoguanabara/git-github#518]
procurei os slides da aula 04 e não encontrei,alguem poderia atualizar pra min?

**Comment by fpacheco3357** [comment]
Não sei do slide, mas gostaria de oferecer um curso de Coach para @gustavoguanabara.
Sei que ele é "fã " dessa "arte". Caso esteja curioso [Clica aqui](https://github.com/fpacheco3357).

PS: É só um teste.
