### ISSUE TITLE
Slide aulas 04

### ISSUE THREAD

**Issue by LucasLuann** [gustavoguanabara/git-github#531]
Estou chateado pois não encontrei o slide da aula 4. Alguem poderia me ajudar? ;p

**Comment by figueiredosoftware** [comment]
boa quero saber também

**Comment by LucasLuann** [comment]
kakakakakakak bons estudos!!

**Comment by figueiredosoftware** [comment]
boa [clica aqui](https://github.com/figueiredosoftware)

**Comment by figueiredosoftware** [comment]
teste

![hk5](https://user-images.githubusercontent.com/68979117/100664416-51e2ca00-3336-11eb-9620-653a6391d428.jpg)

**Comment by MayaraNogueira** [comment]
Respondendo sobre os issue:
Não faço ideia! Espero que tenha ajudado :D
