### ISSUE TITLE
Onde está os slides da Aula 04?

### ISSUE THREAD

**Issue by MatthewBuy** [gustavoguanabara/git-github#553]
Procurei os slides da aula 04 e não encontrei alguém poderia atualizar para mim?

Parabéns pelo curso Gustavo.

**Comment by scram0** [comment]
Após a aula 03, a maioria das aulas foram práticas, portanto não contaram com o apoio dos slides.
Espero ter ajudado!

**Comment by MatthewBuy** [comment]
**Muito obrigado pela sua ajuda!**

Conheça mais meus projetos:
* Meus projetos no [GitHub](https://github.com/MatthewBuy)
* Meu perfil no [Instagram](https://www.instagram.com/matteussouz/)
* Meu perfil no [Linkedin](https://www.linkedin.com/in/mateus-amancio-de-souza-82bb2b174/)
