### ISSUE TITLE
Onde estão os slides da aula 04 ? Treinando issues. Obrigado.

### ISSUE THREAD

**Issue by Gil-Systems** [gustavoguanabara/git-github#566]
Presado professor Gustavo Guanabara.
     Estou cursando o Curso de Git-GitHub e observei a falta dos slides da aula 04. Caso o professor já tenha observado também, desconsidere essa issue e aguardo a postagem. Tenha um boa dia e obrigado.
     Gil-Systems, um aprendiz do Curso em Vídeo.

Ps.: Esta issue faz parte do meu treinamento.

**Comment by adriano-aparecido** [comment]
Seus cursos são muitos bons.
