### ISSUE TITLE
Python

### ISSUE THREAD

**Issue by LuanPetruitis** [gustavoguanabara/git-github#58]
Meu nome é luan estou na faculdade, ainda não tem muita coisa no meu perfil mas tem um repositório de pequenos programas em python, e estou criando alguns em html

**Comment by christyanbrayan** [comment]
posta na issue #3

**Comment by LuanPetruitis** [comment]
não etsá na issue já ?

**Comment by LuanPetruitis** [comment]
Não está na issue?

**Comment by christyanbrayan** [comment]
@LuanPetruitis não está na certa, só ir nesse link e postar lá

**Comment by LuanPetruitis** [comment]
ahh ta vlw
