### ISSUE TITLE
Perfil

### ISSUE THREAD

**Issue by LuanPetruitis** [gustavoguanabara/git-github#59]
Meu nome é luan estou na faculdade, ainda não tem muita coisa no meu perfil mas tem um repositório de pequenos programas em python, e estou criando alguns em html.

Segue lá. E vamos aprender com outras pessoas

**Comment by webkaiyo** [comment]
Olá, @LuanPetruitis! A divulgação de seu perfil e seus projetos devem ser feitas na issue #3, portanto, essa deve ser fechada.

**Comment by LuanPetruitis** [comment]
ahh ta muito obrigado
