### ISSUE TITLE
Certificado GitHub 

### ISSUE THREAD

**Issue by Marcelo-Fonseca** [gustavoguanabara/git-github#599]
Bom dia Professor!!
Desculpa Perguntar aqui, fiz o curso de GitHub lá no site queria emitir o certificado mas não estou conseguindo pois ele aparece 100%  concluído e tem uma mensagem que o curso esta em andamento. poderia me ajudar?

**Comment by YuriKalani** [comment]
Também estou com o mesmo problema. Parece que não vai ter certificado de participação.

**Comment by Dev-Verissimo** [comment]
também estou com esse problema

**Comment by lucashsbarros** [comment]
Também estou tendo o mesmo problema !
