### ISSUE TITLE
Testando MarkDown

### ISSUE THREAD

**Issue by GabrielMerigo** [gustavoguanabara/git-github#617]
# Aula de linguagem **_MarkDown_**
---
Lista Numerada:
1. teste1
2. teste2
1. teste4
6. jojo

**Comment by GabrielMerigo** [comment]
* Teste 
* Teste
* Teste
   * Teste
 * Teste

**Comment by GabrielMerigo** [comment]
Lista de Tarefas:
- [ ] Ganhei na megasena
- [x] Fiquei Pobre

**Comment by GabrielMerigo** [comment]
![apresentação-linkedin](https://user-images.githubusercontent.com/72055874/104390759-2fd78c80-551d-11eb-8d09-914a3282cadc.png)

**Comment by LucasAbreuSantos** [comment]
# Aprendendo Sempre!
***
## Markdown
Aprendendo Linguagem __*Markdown*__ no _Curso de Git-GitHub_ !

**Comment by MCassian0** [comment]
# aprendendo markdown
***
lista numerada
1. teste
1. teste2
2. teste 3
3.teste 4
 4.teste95
   5.teste589
lista demarcada
* teste
* teste
   * teste
 * teste
lista de tarefas :
- [x] pagina inicial
- [x] pagina da loja 
- [ ] finalizar com o cliente
- [ ] receber o money

**Comment by MCassian0** [comment]
![icone](https://user-images.githubusercontent.com/75460968/105610567-fdd0f080-5d8e-11eb-8efd-f736007636a3.png)

**[github]**(https://github.com/MCassian0)

**Comment by MCassian0** [comment]
![icone](https://user-images.githubusercontent.com/75460968/105610919-0aeedf00-5d91-11eb-85dc-12901d84e7b7.png)


[github](https://github.com/MCassian0)

**Comment by MCassian0** [comment]
# tabela
num | nome | nota
---|---|---|
1 | pedro | 9
2 | alex | 5
3 | julia | 7
tabela concluida
