### ISSUE TITLE
Extensões para o Git no VS Code

### ISSUE THREAD

**Issue by jos3s** [gustavoguanabara/git-github#64]
Professor (@gustavoguanabara ) sei que o senhor disse que não mostraria extensões para o VS Code, concordo com isso, porém deveria pelo menos em algum momento citar algumas extensões maravilhosas que existem para melhorar ainda mais essa integração.
Vou recomendar algumas:  

Nome: [Git Graph](https://marketplace.visualstudio.com/items?itemName=mhutchie.git-graph)
Descrição: View a Git Graph of your repository, and perform Git actions from the graph.
Link do VS Marketplace: 

Nome: [GitLens](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens)
Descrição: Supercharge the Git capabilities built into Visual Studio Code — Visualize code authorship at a glance via Git blame annotations and code lens, seamlessly navigate and explore Git repositories, gain valuable insights via powerful comparison commands, and so much more

E essa mais simples, porém que ajuda visualmente:
Nome: [Git Indicators]( https://marketplace.visualstudio.com/items?itemName=lamartire.git-indicators)
Identificação: lamartire.git-indicators
Descrição: Atom like git counters

**Comment by leocunhabr** [comment]
Gostei, só tinha o GitLens os outros dois foram uma uma boa adição, Obrigado.
