### ISSUE TITLE
Como faço para rodar um projeto?

### ISSUE THREAD

**Issue by devgustavotinti** [gustavoguanabara/git-github#653]
Galera, eu fiz o curso porém ficou uma dúvida. 

Quando tiver interesse em ver um projeto, preciso fazer um clone dele e executar na minha máquina  ou tem outros jeitos?

**Comment by iCarlosCode** [comment]
Você pode _visualizar o projeto no GitHub_ ou pode cloná-lo para a sua máquina. Acredito que não há outro jeito além desses dois.

**Comment by devgustavotinti** [comment]
@iCarlosCode quando você diz visualizar o projeto, é apenas ver o código ou tem como acessar o site da pessoa direto pelo github?

**Comment by iCarlosCode** [comment]
É apenas ver o código. 😉👍

**Comment by devgustavotinti** [comment]
@iCarlosCode muito obrigado 🖖

**Comment by iCarlosCode** [comment]
De nada, mano. Estamos aqui pra isso. Agora é a hora em que você fecha a issue, né?

**Comment by devgustavotinti** [comment]
@iCarlosCode valeeu pelo feedback. Abraço.
