### ISSUE TITLE
União de Materiais para estudo de programação em geral - por Eliomar Julian

### ISSUE THREAD

**Issue by Eliomar-Julian** [gustavoguanabara/git-github#70]
### União de Conteúdo de programação para estudo.
Estou reunindo vários materiais da internet e colocando em um único repositório a fim de obter uma organização mais ou menos cronológica para quem está começando em [**Python**](https://eliomar-julian.github.io/python.html), [**Html5/css3**](https://eliomar-julian.github.io/html_css.html), [**JavaScript**](https://eliomar-julian.github.io/javascript.html), [**ShellScript**](https://eliomar-julian.github.io/bash.html), etc.
Para facilitar  estou criando uma pagina no github pages para manter tudo bonitinho.
### <https://www.eliomar-julian.github.io>
podem visitar meu perfil aqui: <https://github.com/Eliomar-Julian/>
### Esboço do Trabalho abaixo
![*Esboço do trabalho*](https://github.com/Eliomar-Julian/Eliomar-Julian.github.io/raw/master/imagens/Captura%20de%20Tela%20(1).png)
>agradecimentos especiais ao **@gustavoguanabara**
>e a toda essa galera linda do Curso em Vídeo
>por proporcionar esse conteúdo inestimável gratuitamente
>para nós

**Comment by Eliomar-Julian** [comment]
Ola meu nome é Eliomar Julian e sou um entusiasta de programação.

**Comment by Namelangless-hub** [comment]
**Oi galera**
