### ISSUE TITLE
dificuldades para criar um novo repositorio no github desktop

### ISSUE THREAD

**Issue by thiagosales007** [gustavoguanabara/git-github#767]
bom dia
poderia me ajudar não estou conseguindo criar um novo repositorio no github desktop
esta aparecendo esta imagem.
agradeço pela ajuda. 👍 

![image](https://user-images.githubusercontent.com/80003710/110949764-c065f980-8321-11eb-881c-0ddc331250e2.png)

**Comment by DevAndreMendes** [comment]
oi boa noite.
Seu problema já está resolvido?

**Comment by thiagosales007** [comment]
bom dia,
nao ainda estou com o mesmo problema infelizmente
você sabe como resolver??

**Comment by DevAndreMendes** [comment]
Poderia me explicar melhor o que está acontecendo? Você consegue digitar o nome no qual quer colocar no repositório?

**Comment by thiagosales007** [comment]
bom dia
deu certo consegui
o problema era no *Local path*, eu tinha que criar e renomear uma pasta nova para o meu projeto novo.
erro de principiante deu tudo certo.
mesmo assim obrigado @DevAndreMendes pela ajuda 👍 🤝
