### ISSUE TITLE
Issue para agradecer o Guanabara👍

### ISSUE THREAD

**Issue by guilherme30** [gustavoguanabara/git-github#788]
Obrigado pelas aulas Guanabara! Estou aprendendo muito...

**Comment by gabiiebr** [comment]
Obrigada pelas aulas, dá uma olhada na Assinatura Padrão maneira que eu fiz!

### Muito obrigada por sua colaboração!
![assinatura preta](https://user-images.githubusercontent.com/77301857/112087983-bfc53280-8b6d-11eb-9d1c-d5a8a51f165c.png)
