### ISSUE TITLE
Onde está os slides da aula 04? #5

### ISSUE THREAD

**Issue by jonathancbrito** [gustavoguanabara/git-github#824]
Procurei os slides da aula 4 e não encontrei,
Alguém poderia atualizar pra mim?

**Comment by wicthordavid** [comment]
Caro colega @JonathanCB99! A aula 04 do Curso de Git e GitHub não tem slides! Ela foi uma aula prática que você pode acessar [diretamente clicando aqui](https://www.youtube.com/playlist?list=PLHz_AreHm4dm7ZULPAmadvNhH6vk9oNZA) <hr>
![g2924](https://user-images.githubusercontent.com/80369999/112766736-77809700-8fe9-11eb-8aad-5b1a986193b6.png)

**Comment by JuniorMoura10** [comment]
O correto seria "onde estÃO os slides..." já que está no plural! rsrs

**Comment by wicthordavid** [comment]
Que infelicidade, lembrar de deixar de seguir a Issue só quando visualizar um comentário infeliz de uma pessoa carente.

**Comment by vitoriamillnitz** [comment]
fazendo o curso de git e github now :)

**Comment by TalesPorto99** [comment]
Já está atualizado!!
Reta final do curso de Git e GitHub...

**Comment by ghost** [comment]
Fazendo o teste do slide da aula 4. Agradeço demais ao professor Guanabara e a Hostnet pelo ótimo curso. Parabéns pela iniciativa, estou aprendendo muito!
