### ISSUE TITLE
testando markdown

### ISSUE THREAD

**Issue by jonathancbrito** [gustavoguanabara/git-github#825]
teste de linguagem markdown

**Comment by raphaellimalm** [comment]
# *Testando Markdow*
- [X] *@raphaellimalm*
Acesse meu *LinkedIn* (https://www.linkedin.com/in/raphaellimadasilva/)

Numero | Nome | Nota
---|---|---
00|Raphael Lima|0
:infinity:  | :computer_mouse:| :bomb:

**Comment by raylasilva** [comment]
__TABELA ESCOLAR__

NOME | TURMA | NOTA
---|---|---
RAYLA | 003 | 10
PEDRO|002|8
JONATAS|001|10
