### ISSUE TITLE
Vai ter Certificado de Participação?

### ISSUE THREAD

**Issue by Albervan** [gustavoguanabara/git-github#88]
# Fala grande Mestre, @gustavoguanabara !

### Primeiramente o curso está sendo **excelente**!
> ### Muito Obrigado!

_Eu gostaria de saber se você vai dar um certificado de participação do Curso._

Seria muito útil para fazermos **divulgação** nas redes sociais, além de ser **muito prazeroso** fazer um **curso de qualidade** desses e ter uma comprovação oficial!
> ### Muito obrigado pela sua colaboração!
---
![Assinatura para Web](https://user-images.githubusercontent.com/54541416/79019007-48a4b300-7b43-11ea-8efc-d3fa38a16958.png)

Conheça mais:
* [LinkedIn](https://www.linkedin.com/in/albervan-bergamasco-davies-15aa9999/)
* [Repositórios públicos no GitHub](https://github.com/Albervan)
* [Wordpress](https://albervan.wordpress.com/)

**Comment by christyanbrayan** [comment]
@Albervan ele disse que não vai ter.
Vc pode divulgar o seu perfil e links na issue #3 que foi feita pra isso, se puder fechar essa p dar uma limpada por aqui

**Comment by Albervan** [comment]
> @Albervan ele disse que não vai ter.
> Vc pode divulgar o seu perfil e links na issue #3 que foi feita pra isso, se puder fechar essa p dar uma limpada por aqui

Obrigado pela informação @christyanbrayan !
Eu não estou acompanhando as aulas durante as lives, por isso devo ter perdido esse comentario do @gustavoguanabara .

Mas de qualquer forma meu interesse é divulgar o curso em minhas redes sociais. O meu perfil já coloquei na Issue #3 .

Bom, como já tenho a resposta que queria, vou encerrar essa Issue.

Obrigado!

![Assinatura para Web](https://user-images.githubusercontent.com/54541416/79019007-48a4b300-7b43-11ea-8efc-d3fa38a16958.png)

Conheça mais:
* [LinkedIn](https://www.linkedin.com/in/albervan-bergamasco-davies-15aa9999/)
* [Repositórios públicos no GitHub](https://github.com/Albervan)
* [Wordpress](https://albervan.wordpress.com/)
