### ISSUE TITLE
Índice das aulas nos vídeos do Youtube

### ISSUE THREAD

**Issue by bapds** [gustavoguanabara/git-github#9]
Boa noite Professor, seria possível adicionar um índice de ordenação nos vídeos do curso de Git?

Agradeço.

**Comment by vcwild** [comment]
Boa noite @bapds , quando o professor @gustavoguanabara  inseriu os vídeos na playlist de Git e GitHub eles automaticamente receberam um índice, como pode ser verificado na imagem em anexo.
![indice_git](https://user-images.githubusercontent.com/49621396/78841903-f9d90b00-79d4-11ea-9769-4400bdfbfa7e.png)

**Comment by gustavoguanabara** [comment]
Obrigado @vcwild ! O espírito é exatamente esse! Muito obrigado pela colaboração tão bem ilustrada!

Você também pode [acessar a playlist completa do curso de Git e GitHub](https://www.youtube.com/playlist?list=PLHz_AreHm4dm7ZULPAmadvNhH6vk9oNZA)
