### ISSUE TITLE
Como inserir uma imagem no Readme?

### ISSUE THREAD

**Issue by ronanProg** [gustavoguanabara/git-github#91]
Estou tentando inserir uma pequena imagem ao lado do meu titulo do readme do meu repositório para ficar mais estilizado  e também para treinar um pouco a linguagem Markdwon.Isso é possível?Alguém pode me ajudar?

Obs:Estou criando repositório que contém meus exercícios resolvidos:
 ronanProg /Curso-em-Video 
 ronanProg /Estudonauta

**Comment by leocunhabr** [comment]
# Titulo ![8683378](https://user-images.githubusercontent.com/3671475/79053963-a3a7da00-7c17-11ea-82a6-2ff6240e353a.png)

Seria esse o seu objetivo?

**Comment by ronanProg** [comment]
Sim @leocunhabr .Mas não consigo inserir o diretório da imagem.Estou usando linux mint não sei se isso interfere.

**Comment by leocunhabr** [comment]
Acho que entendi você quer pegar a imagem diretamente do seu repositório.

Você pode usar esse caminho abaixo.
```
![Alt Text](https://github.com/{user}/{repo}/raw/{branch}/path/to/image.png)
```
Você tem que subir todas as imagens e depois colocar os caminhos delas.

OBS:. Tem que ser um caminho absoluto para ser reconhecido o caminho.

**Comment by ronanProg** [comment]
@leocunhabr então é necessário upar a imagem para o repositório remoto e depois inserir na formtação,é isso?Estava tentando pegar no diretório do próprio PC fora do repositório e inseri-lo.

**Comment by leocunhabr** [comment]
@ronanProg Exatamente, o caminho tem que ser absoluto, até aonde eu sei, você tem que colocar o caminho inteiro da imagem, a imagem fica com outro caminho quando você coloca no github, não reconhece um caminho que estava no seu computador.

**Comment by ronanProg** [comment]
@leocunhabr fiz isso que você me disse.Mas ainda não consegui.Exibe a mema coisa de antes.Acho que não estou acertando o diretório.

`# Curso-em-Video ![curso-em-video](https://github.com/ronanProg/Curso-em-Video/logo-curso-em-video-oficial.png)`

**Comment by willfpinheiro** [comment]
@ronanProg Fiz um **PullRequest** com uma sugestão de solução. 
* Podendo usar dessa forma
Reference-style: ![alt text][logo]

[logo]: https://github.com/adam-p/markdown-here/raw/master/src/common/images/icon48.png "Logo Title Text 2"
* Dessa forma, com mudança de tamanho
HTML <img src="https://github.com/adam-p/markdown-here/raw/master/src/common/images/icon48.png" alt="Minha Figura" width="32" height="32">

**Comment by ronanProg** [comment]
@willfpinheiro obrigado pela sugestão e solução do problema.Mas ainda não entendo o diretório.Aparece um blob, o que significa isso no diretorio?
`# Curso-em-Video <img src="https://github.com/ronanProg/Curso-em-Video/blob/master/logo-curso-em-video-oficial.png"  width="60" height="38" />`

**Comment by ronanProg** [comment]
@leocunhabr  e @willfpinheiro  obrigado pela ajuda.Me ajudaram bastante na solução do problema. :+1:
