### ISSUE TITLE
Testando a Linguagem Markdown

### ISSUE THREAD

**Issue by david-jc-br** [gustavoguanabara/git-github#916]
# Testando  1
---
## Testando 2
***
### Testando 3 
---
#### Testando 4
---
#####  Testando 5
***
######  Testando 6 (máximo)
---
Testando a linguagem **Markdown** 

Testando a Linguagem ~~Markdown~~

Testando a Linguagem *Markdown*

Testando a Linguagem _Markdown_

**Comment by david-jc-br** [comment]
Testando _**misturar**_ hahah

Lista

1. Teste1
2. Teste 2 
   1. Subtopico do 2
   2. Automático
   3. automático 
   4. Tem que dar 3 espaços 
3. Teste 3
0. Teste 0

Lista Demarcada 

- teste
- teste
   - teste

* Teste
* teste 
  * teste  três espaços 
  * de novo 
*  teste y
* teste

Lista de tarefas 

- [ ] traço, espaço, abre colchetes, espaço, fecha colchetes.
- [x] Teste
- [ ] teste
- [X] feito 
- [X] feito 2

**Comment by david-jc-br** [comment]
Lista de tarefas 

- [ ] traço, espaço, abre colchetes, espaço, fecha colchetes.
- [X] Teste
- [ ] teste
- [X] feito 
- [X] feito 2

**Comment by david-jc-br** [comment]
![image](https://user-images.githubusercontent.com/73839667/117061389-80573d80-acf8-11eb-9d32-fa736e0afc4e.png)

[Clique aqui para baixar a imagem](https://octodex.github.com/manufacturetocat/)

[]()

**Comment by david-jc-br** [comment]
# Tabela de teste

*nome* | Nota | idade | Aprovado 
---|---|---|---
~~David~~ | 15,9 | 19 | sim 
terminou

dois enter(s), agora sim terminou

**Comment by david-jc-br** [comment]
# Olha Meu Programa em C++ [Teste]
```
#include iostream 
using namespace std;

int main () {
    cout << "Aprendendo linguagem que não é de Programação Markdown " << endl;
    return 0;
}
```

**Comment by david-jc-br** [comment]
Olá Pessoas 👍🏽 

Testando 🆗 

sla 🐾 

hand ✋🏽 

house 🏡 dog 🐶 

ponha os dois pontos e escreva o nome do emoji em inglês.

**Comment by Cerrulatos** [comment]
Estou aprendendo a ~~linguagem~~ **Markdown** no *curso em vídeo* de Git e GitHub
#Nível 1
##Nível 2
###Nível 3
***

__*Lista numerada*__
1. Texto 1
   1. sub texto
   2. sub texto
2. Texto 2
3. Texto 3
---
__*Lista de tarefas*__
- [x] Tarefa 1
- [x] Tarefa 2
- [ ] Tarefa 3
- [ ] Tarefa 4
- [ ] Tarefa 5

[Aqui tem um link top, clique para ver a mágica acontecer. rs](https://github.com/Cerrulatos)

Num | Nome | Nota
---|---|---
1 | Gustavo | 8,5
2 | Marco | 10
3 | Bateria | 7,5
4 | Enredo | 5,5
---

Estou aprendendo `Python` e veja que legal esse comando: 👍🏻 💇🏻 🖖🏻 
```
print("Hello world!")
```
