### ISSUE TITLE
Olá, meu nome é Amir.

### ISSUE THREAD

**Issue by Amir258** [gustavoguanabara/git-github#92]
# Criei a issue sem querer
---
Era pra ser no divulgue seu perfil 😁 
_Ainda estou aprendendo_

**Comment by christyanbrayan** [comment]
@Amir258 fecha essa issue

**Comment by Amir258** [comment]
> 
> 
> @Amir258 fecha essa issue

Não da pra eu fechar

**Comment by Amir258** [comment]
> 
> 
> @Amir258 fecha essa issue

Pronto.
