### ISSUE TITLE
Como posso mencionar uma pessoa no meu repositório

### ISSUE THREAD

**Issue by ronanProg** [gustavoguanabara/git-github#96]
Estou tentando mencionar o @gustavoguanabara  em meu repositório mas não estou conseguindo.Algúem pode me ajudar?

Eu tentei assim:

`@https://github.com/gustavoguanabara`

**Comment by leocunhabr** [comment]
Se estiver falando do README, você tem que criar um link com referência ao perfil do Guanabara.

**Comment by ronanProg** [comment]
@leocunhabr obrigado.Solucionou o meu problema.
