### ISSUE TITLE
Tem alguma forma de colocar meus arquivos de Visualg no GitHub ? 

### ISSUE THREAD

**Issue by gui-hub-web** [gustavoguanabara/git-github#97]
Eu gostaria de saber como enviar meus programas do Visualg para o GitHub.

**Comment by ronanProg** [comment]
olá @gui-hub-web , segue os passos:
1. Criar  o repositório local 
1. Transferir seu arquivos para esse repositório 
1. Dar um commit
1. E dar um push

O @gustavoguanabara ensinou isso no [vídeo 7](https://www.youtube.com/watch?v=065NQCDSMb0&list=PLHz_AreHm4dm7ZULPAmadvNhH6vk9oNZA&index=7) do curso de GitHub.

**Comment by bruno1409** [comment]
Exatamente o que o @ronanProg falou, inclusive eu tenho alguns arquivos do VisuAlg no meu repositório **algoritmos**. Eles não ficam coloridos como em outras linguagens, mas o versionamento funciona perfeitamente.

**Comment by gui-hub-web** [comment]
**Muito obrigado pessoal ! 👍 **

*Consegui colocar agora, se quiserem dar uma olhada é uma especie de "calculadora".*
